/*
 * Inference for Llama-2 Transformer model in pure C (No Quantization).
 *
 * This version is adapted for bare-metal execution. All model and tokenizer data
 * is embedded directly into the executable using header files generated by `xxd`.
 * This removes the dependency on a filesystem for loading data.
 *
 * Key Modifications:
 * 1.  Inclusion of `stories_data.h` and `tok512.h` which contain the model
 * and tokenizer data as C arrays.
 * 2.  All quantization-related logic (`QuantizedTensor`, `quantize`, `dequantize`, etc.)
 * has been removed. The model now operates directly on float32 weights.
 * 3.  `build_transformer` and `build_tokenizer` are modified to read from these
 * in-memory arrays instead of from files.
 * 4.  `free_transformer` is adjusted to not free the main data pointer, as it
 * now points to static data in the executable's data segment.
 * 5.  Command-line argument parsing for file paths has been removed.
 * 6.  Global variables for Board Support Package (BSP) are included for
 * hardware-specific configurations (e.g., UART, timers).
 */

#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <stdint.h>
#include <time.h>
#include <math.h>
#include <string.h>
#include <malloc.h>
#if defined _WIN32
    #include "win.h"
#else
    #include <unistd.h>
#endif

// ----------------------------------------------------------------------------
// Board Support Package (BSP) Globals for Bare-Metal Target
// These variables would be configured for the specific hardware.
unsigned long UART_BASE = 0xbf000000;              // UART16550的虚地址
unsigned long CB_BASE = 0xbf300000;
unsigned long CONFREG_TIMER_BASE = 0xbf20f100;      // CONFREG计数器的虚地址
unsigned long CONFREG_CLOCKS_PER_SEC = 50000000L;   // CONFREG时钟频率
unsigned long CORE_CLOCKS_PER_SEC = 33000000L;      // 处理器核时钟频率
unsigned long RANDOM_BASE = 0xbf20f600;             // 改为uncached窗口(0xbf..)，MMIO必须非缓存访问，否则cache突发读挂死单拍confreg
unsigned long SWITCH_BASE = 0xbf20f400;             // 同上，与UART/TIMER/CB地址前缀对齐

// ----------------------------------------------------------------------------
// Embedded Data Headers
// These files are generated by a tool like `xxd -i model.bin > model.h`.
// They contain the raw model and tokenizer data as C arrays.
#include "stories_data.h" // Defines stories_bin[] and stories_bin_len
#include "tok512.h"       // Defines tok512_bin[] and tok512_bin_len
#include "hw_accelerator.h" // Hardware accelerator definitions
#include "common_func.h"
#include "confreg_time.h"

// ----------------------------------------------------------------------------

static inline void cpu_idle(void)
{
    __asm__ __volatile__("idle 0" ::: "memory");
}

static inline void cb_write(unsigned long offset, unsigned long value)
{
    RegWrite(CB_BASE + offset, value);
}

static inline unsigned long cb_read(unsigned long offset)
{
    return RegRead(CB_BASE + offset);
}

void HWI1_IntrHandler(void){
    cb_write(REG_CTRL_ADDR, 0);
}

// Data Structures

typedef struct {
    int dim;        // transformer dimension
    int hidden_dim; // for FFN layers
    int n_layers;   // number of layers
    int n_heads;    // number of query heads
    int n_kv_heads; // number of key/value heads (can be < n_heads)
    int vocab_size; // vocabulary size
    int seq_len;    // max sequence length
} Config;

typedef struct {
    // token embedding table
    float* token_embedding_table;   // (vocab_size, dim)
    // weights for rmsnorms
    float* rms_att_weight;          // (layer, dim) rmsnorm weights
    float* rms_ffn_weight;          // (layer, dim)
    // weights for matmuls
    float* wq;                      // (layer, dim, n_heads * head_size)
    float* wk;                      // (layer, dim, n_kv_heads * head_size)
    float* wv;                      // (layer, dim, n_kv_heads * head_size)
    float* wo;                      // (layer, n_heads * head_size, dim)
    // weights for ffn
    float* w1;                      // (layer, hidden_dim, dim)
    float* w2;                      // (layer, dim, hidden_dim)
    float* w3;                      // (layer, hidden_dim, dim)
    // final rmsnorm
    float* rms_final_weight;        // (dim,)
    // classifier weights
    float* wcls;
} TransformerWeights;

typedef struct {
    // current wave of activations
    float *x;           // activation at current time stamp (dim,)
    float *xb;          // same, but inside a residual branch (dim,)
    float *xb2;         // an additional buffer for convenience (dim,)
    float *hb;          // buffer for hidden dimension in FFN (hidden_dim,)
    float *hb2;         // buffer for hidden dimension in FFN (hidden_dim,)
    float *q;           // query (dim,)
    float *k;           // key (kv_dim,)
    float *v;           // value (kv_dim,)
    float *att;         // buffer for scores/attention values (n_heads, seq_len)
    float *logits;      // output logits
    // kv cache
    float* key_cache;   // (layer, seq_len, kv_dim)
    float* value_cache; // (layer, seq_len, kv_dim)
} RunState;

typedef struct {
    Config config;
    TransformerWeights weights;
    RunState state;
    // pointer to the embedded model data
    float* data;
    size_t file_size;
} Transformer;

// ----------------------------------------------------------------------------
// Memory allocation and management

void malloc_run_state(RunState* s, Config* p) {
    int kv_dim = (p->dim * p->n_kv_heads) / p->n_heads;
    int head_size = p->dim / p->n_heads;
    int n_kv_heads = p->n_kv_heads;
    int max_tiles = (p->seq_len + head_size - 1) / head_size;
    int tile_size = n_kv_heads * head_size * head_size; // 每tile的float数
    s->x = calloc(p->dim, sizeof(float));
    s->xb = calloc(p->dim, sizeof(float));
    s->xb2 = calloc(p->dim, sizeof(float));
    s->hb = calloc(p->hidden_dim, sizeof(float));
    s->hb2 = calloc(p->hidden_dim, sizeof(float));
    s->q = calloc(p->dim, sizeof(float));
    s->k = calloc(kv_dim, sizeof(float));
    s->v = calloc(kv_dim, sizeof(float));
    s->att = calloc(p->n_heads * p->seq_len, sizeof(float));
    s->logits = calloc(p->vocab_size, sizeof(float));
    // KV cache使用tile-based布局，直接对应硬件DMA格式
    // 布局: [layer][tile][n_kv_heads × head_size × head_size]
    s->key_cache = calloc(p->n_layers * max_tiles * tile_size, sizeof(float));
    s->value_cache = calloc(p->n_layers * max_tiles * tile_size, sizeof(float));
    // ensure all mallocs were successful
    if (!s->x || !s->xb || !s->xb2 || !s->hb || !s->hb2 || !s->q
     || !s->k || !s->v || !s->att || !s->logits || !s->key_cache || !s->value_cache) {
        fprintf(stderr, "malloc failed in malloc_run_state!\n");
        exit(EXIT_FAILURE);
    }
}

void free_run_state(RunState* s) {
    free(s->x); free(s->xb); free(s->xb2); free(s->hb); free(s->hb2);
    free(s->q); free(s->k); free(s->v);
    free(s->att); free(s->logits);
    free(s->key_cache); free(s->value_cache);
}

void memory_map_weights(TransformerWeights *w, Config* p, float* ptr, int shared_weights) {
    int head_size = p->dim / p->n_heads;
    // make sure the multiplications below are done in 64bit to fit the parameter counts of 13B+ models
    unsigned long long n_layers = p->n_layers;
    w->token_embedding_table = ptr;
    ptr += p->vocab_size * p->dim;
    w->rms_att_weight = ptr;
    ptr += n_layers * p->dim;
    w->wq = ptr;
    ptr += n_layers * p->dim * (p->n_heads * head_size);
    w->wk = ptr;
    ptr += n_layers * p->dim * (p->n_kv_heads * head_size);
    w->wv = ptr;
    ptr += n_layers * p->dim * (p->n_kv_heads * head_size);
    w->wo = ptr;
    ptr += n_layers * (p->n_heads * head_size) * p->dim;
    w->rms_ffn_weight = ptr;
    ptr += n_layers * p->dim;
    w->w1 = ptr;
    ptr += n_layers * p->dim * p->hidden_dim;
    w->w2 = ptr;
    ptr += n_layers * p->hidden_dim * p->dim;
    w->w3 = ptr;
    ptr += n_layers * p->dim * p->hidden_dim;
    w->rms_final_weight = ptr;
    ptr += p->dim;
    ptr += p->seq_len * head_size / 2; // skip what used to be freq_cis_real (for RoPE)
    ptr += p->seq_len * head_size / 2; // skip what used to be freq_cis_imag (for RoPE)
    w->wcls = shared_weights ? w->token_embedding_table : ptr;
}

// CORRECTED: The order of operations in this function is now correct.
void build_transformer(Transformer *t) {
    // MODIFICATION: Instead of opening a file, point directly to the embedded data array.
    t->data = (float*)stories_bin;
    t->file_size = stories_bin_len;

    // Read the header metadata from the beginning of the data block
    float* data_ptr = t->data;

    // --- FIX START ---
    // 1. First, copy the config from the data blob into the transformer struct.
    memcpy(&t->config, data_ptr, sizeof(Config));

    // 2. Now that t->config is populated, we can use its values.
    // The negative vocab_size is a hacky way of signaling unshared weights.
    int shared_weights = t->config.vocab_size > 0 ? 1 : 0;
    t->config.vocab_size = abs(t->config.vocab_size);
    
    // 3. The weights start right after the config header.
    float* weights_ptr = data_ptr + (sizeof(Config) / sizeof(float));
    memory_map_weights(&t->weights, &t->config, weights_ptr, shared_weights);
    // --- FIX END ---

    // Allocate memory for the run state
    malloc_run_state(&t->state, &t->config);
}

void free_transformer(Transformer* t) {
    // MODIFICATION: Do NOT free t->data, as it points to a static array
    // in the executable's data segment, not heap-allocated memory.
    // if (t->data != NULL) {
    //     free(t->data);
    // }
    
    // Free the run state buffers
    free_run_state(&t->state);
}


// ----------------------------------------------------------------------------
// Neural net layers

void rmsnorm(float* o, float* x, float* weight, int size) {
    // calculate sum of squares
    float ss = 0.0f;
    for (int j = 0; j < size; j++) {
        ss += x[j] * x[j];
    }
    ss /= size;
    ss += 1e-5f;
    ss = 1.0f / sqrtf(ss);
    // normalize and scale
    for (int j = 0; j < size; j++) {
        o[j] = weight[j] * (ss * x[j]);
    }
}

void softmax(float* x, int size) {
    if (size == 1) { x[0] = 1.0f; return; }
    // find max value (for numerical stability)
    float max_val = x[0];
    for (int i = 1; i < size; i++) {
        if (x[i] > max_val) {
            max_val = x[i];
        }
    }
    // exp and sum
    float sum = 0.0f;
    for (int i = 0; i < size; i++) {
        x[i] = expf(x[i] - max_val);
        sum += x[i];
    }
    // normalize
    for (int i = 0; i < size; i++) {
        x[i] /= sum;
    }
}

// void matmul(float* xout, float* x, float* w, int n, int d) {
//     // W (d,n) @ x (n,) -> xout (d,)
//     // by far the most amount of time is spent inside this function
//     int i;
//     #pragma omp parallel for private(i)
//     for (i = 0; i < d; i++) {
//         float val = 0.0f;
//         for (int j = 0; j < n; j++) {
//             val += w[i * n + j] * x[j];
//         }
//         xout[i] = val;
//     }
// }
static int matmul_mismatch_count = 0;
static int matmul_call_count = 0;
#define EPSILON 1e-6f
#ifndef CPU_ONLY_MATMUL
#define CPU_ONLY_MATMUL 0
#endif
#ifndef BENCH_MATMUL_REPORT_INTERVAL
#define BENCH_MATMUL_REPORT_INTERVAL 0
#endif
#ifndef BENCH_TOKEN_REPORT_INTERVAL
#define BENCH_TOKEN_REPORT_INTERVAL 0
#endif

#ifndef VERIFY_MATMUL
#define VERIFY_MATMUL 0
#endif

static unsigned long long bench_matmul_calls = 0;
static unsigned long long bench_matmul_cycles_total = 0;
#if VERIFY_MATMUL
static int verify_total_calls = 0;
static int verify_mismatch_calls = 0;
static float verify_global_max_err = 0.0f;
static double verify_err_sum = 0.0;
static int verify_total_elements = 0;
static int verify_total_mismatches = 0;
static int verify_fail_by_n[8];
static int verify_fail_n_vals[8];
static int verify_n_bucket_cnt = 0;

static int verify_fsa_calls = 0;
static int verify_fsa_mismatch_calls = 0;
static float verify_fsa_global_max_err = 0.0f;

static int verify_find_bucket(int n) {
    for (int i = 0; i < verify_n_bucket_cnt; i++)
        if (verify_fail_n_vals[i] == n) return i;
    if (verify_n_bucket_cnt < 8) {
        verify_fail_n_vals[verify_n_bucket_cnt] = n;
        verify_fail_by_n[verify_n_bucket_cnt] = 0;
        return verify_n_bucket_cnt++;
    }
    return -1;
}
#endif

static inline void cache_flush(void *addr, size_t size)
{
    unsigned long line = 1 << cache_offset_width;
    unsigned long start = ((unsigned long)addr) & ~(line - 1);
    unsigned long end = ((unsigned long)addr + size + line - 1) & ~(line - 1);
    for (unsigned long p = start; p < end; p += line) {
        __asm__ __volatile__("cacop 0x11, %0, 0" :: "r"(p) : "memory");
    }
    __asm__ __volatile__("dbar 0" ::: "memory");
}

void matmul(float* xout, float* x, float* w, int n, int d) {
    unsigned long start_cycles = get_cpu_clock_count();
#if CPU_ONLY_MATMUL
    for (int i = 0; i < d; i++) {
        float sum = 0.0f;
        for (int j = 0; j < n; j++) {
            sum += w[i * n + j] * x[j];
        }
        xout[i] = sum;
    }
#else
    // // 硬件控制器将负责内部的分块循环和地址计算。
    // matmul_call_count++;
    // printf("matmul call #%d: xout=%p, x=%p, w=%p, n=%d, d=%d\n",
    //        matmul_call_count, (void*)xout, (void*)x, (void*)w, n, d);
    // printf("matmul_call_count is %d\n",matmul_call_count);
    

    // printf("Go into matmul!\n");
    // //count by cpu
    // float* cpu_out = (float*)malloc(sizeof(float) * d);
    // if (!cpu_out) {
    //     fprintf(stderr, "matmul: failed to malloc cpu_out\n");
    //     return;
    // }

    // // CPU 版本计算
    // // #pragma omp parallel for
    // for (int i = 0; i < d; i++) {
    //     float sum = 0.0f;
    //     for (int j = 0; j < n; j++) {
    //         sum += w[i * n + j] * x[j];
    //     }
    //     cpu_out[i] = sum;
    // }


    // 设置整个权重矩阵 w、输入向量 x 和输出向量 xout 的起始基地址。
    cb_write(REG_MI_BASE_ADDR, (unsigned long)w);
    cb_write(REG_VI_BASE_ADDR, (unsigned long)x);
    cb_write(REG_VO_BASE_ADDR, (unsigned long)xout);

    //Software Cache flush
    cache_flush(x, (size_t)n * sizeof(float));
    cache_flush(w, (size_t)n * (size_t)d * sizeof(float));
    cache_flush(xout, (size_t)d * sizeof(float));

    // 设置整个任务的总维度 (例如，对于64x64矩阵，d=64, n=64)。
    cb_write(REG_ROWS_ADDR, d);
    cb_write(REG_COLS_ADDR, n);

    //TODO cache flush

    // --- 2. 启动硬件引擎 ---
    // 发送一个启动命令。硬件控制器收到后，将开始其内部分块循环。
    cb_write(REG_CTRL_ADDR, CSR_CTRL_START_BIT);

    // --- 3. 等待硬件完成整个大任务 ---
    cpu_idle();

    // --- 4. 应答中断 ---
    HWI1_IntrHandler();

#if VERIFY_MATMUL
    // CPU对比验证
    {
        verify_total_calls++;
        int mismatch = 0;
        float max_err = 0.0f;
        int max_err_idx = 0;
        double err_sum_local = 0.0;
        for (int i = 0; i < d; i++) {
            float cpu_val = 0.0f;
            for (int j = 0; j < n; j++) {
                cpu_val += w[i * n + j] * x[j];
            }
            float diff = fabsf(cpu_val - xout[i]);
            err_sum_local += diff;
            if (diff > max_err) {
                max_err = diff;
                max_err_idx = i;
            }
            if (diff > 1e-2f) {
                mismatch++;
            }
        }
        verify_total_elements += d;
        verify_err_sum += err_sum_local;
        if (max_err > verify_global_max_err)
            verify_global_max_err = max_err;
        if (mismatch > 0) {
            verify_mismatch_calls++;
            verify_total_mismatches += mismatch;
            int b = verify_find_bucket(n);
            if (b >= 0) verify_fail_by_n[b]++;
            printf("[VERIFY] FAIL call#%d d=%d n=%d mismatches=%d max_err=%.6f@idx=%d\n",
                   verify_total_calls, d, n, mismatch, max_err, max_err_idx);
        } else if ((verify_total_calls % 64) == 0) {
            printf("[VERIFY] OK call#%d max_err=%.6f\n", verify_total_calls, max_err);
        }
    }
#endif

    //     for (int i = 0; i < d; i++) {
    //     float a = cpu_out[i];
    //     float b = xout[i];
    //     if (fabsf(a - b) > EPSILON) {
    //         matmul_mismatch_count++;
    //         printf("  [Mismatch] idx=%d, CPU=%f, CB=%f, diff=%f\n",
    //                i, a, b, fabsf(a - b));
    //     }
    // }
    // if (matmul_mismatch_count == 0) {
    //     printf("  All %d elements match ✅\n", d);
    // } else {
    //     printf("  *** Total mismatches: %d ***\n", matmul_mismatch_count);
    // }

    // free(cpu_out);
    // while(1);
#endif

    {
        unsigned long end_cycles = get_cpu_clock_count();
        unsigned long delta = end_cycles - start_cycles;
        bench_matmul_calls++;
        bench_matmul_cycles_total += (unsigned long long)delta;
#if BENCH_MATMUL_REPORT_INTERVAL > 0
        if ((bench_matmul_calls % BENCH_MATMUL_REPORT_INTERVAL) == 0) {
            unsigned long long avg_cycles = bench_matmul_cycles_total / bench_matmul_calls;
            printf("\n[BENCH] matmul_progress calls=%llu total_cycles=%llu avg_cycles=%llu\n",
                   bench_matmul_calls, bench_matmul_cycles_total, avg_cycles);
        }
#endif
    }
}


// ============================================================================
// FSA硬件加速Attention
// ============================================================================

// FSA工作缓冲区（静态分配，避免每次malloc）
static float fsa_q_buf[4 * 8] __attribute__((aligned(16)));
static float fsa_o_buf[4 * 8] __attribute__((aligned(16)));

// 将K/V向量scatter到tile-based cache布局
// cache布局: [layer][tile][n_kv_heads × head_size × head_size]
static void store_kv_to_cache(float* cache, int loff, int pos,
                               float* kv_vec, int kv_dim, int head_size) {
    int tile_idx = pos / head_size;
    int row_in_tile = pos % head_size;
    int n_kv_heads = kv_dim / head_size;

    for (int g = 0; g < n_kv_heads; g++) {
        float* dst = cache + loff + tile_idx * n_kv_heads * head_size * head_size
                   + g * head_size * head_size + row_in_tile * head_size;
        float* src = kv_vec + g * head_size;
        memcpy(dst, src, head_size * sizeof(float));
    }
}

// FSA硬件在4×8分组下每趟处理4个Q组（NUM_ACTIVE=4）。这是硬件几何常量，
// 不是模型参数——它决定一趟能并行几个head、以及Q/O工作缓冲的容量。
#define FSA_NUM_ACTIVE 4

// FSA模式硬件加速attention（GQA fanout版）
//
// 硬件已支持"一份KV读一次、写Input SRAM时广播到ratio个Q组"（见CB_top_v2.sv
// 的k/v_fanout_bank_we）。软件侧据此重排分趟，让每个唯一KV头只从DDR读一次：
//   ratio       = kv_mul：每个KV头被kv_mul个连续Q头共享 → 硬件fanout到ratio个组
//   kv_per_pass = NUM_ACTIVE/ratio：一趟硬件实际只读这么多个唯一KV头
//   num_passes  = n_heads/NUM_ACTIVE：覆盖全部Q头需要的趟数
//
// stories260K(n_heads=8,n_kv_heads=4,kv_mul=2)：ratio=2,kv_per_pass=2,num_passes=2
//   pass0: Q0..3 → 读KV0,KV1，fanout KV0→组{0,1}、KV1→组{2,3}
//   pass1: Q4..7 → 读KV2,KV3，fanout KV2→组{0,1}、KV3→组{2,3}
//   KV总读量4次（每头一次），旧版每趟读全部4头共8次 → 省50% DDR读带宽。
//
// 关键：组g的Q头=pass*NUM_ACTIVE+g，其KV头=(pass*NUM_ACTIVE+g)/kv_mul，与硬件
// fanout映射（本趟local KV头kvh→组{kvh*ratio..kvh*ratio+ratio-1}）逐组吻合。
//
// 该重排只在参数满足"fanout整齐分解"时成立（见fsa_fanout_ok），否则退回旧的
// 每趟读全部n_kv_heads头的多趟逻辑（attention_fsa_legacy），保证任意合法config
// 都正确（只是不省带宽）。stories260K满足条件，走fanout快路径。
static void attention_fsa_fanout(RunState* s, Config* p, int pos, int loff) {
    int head_size = p->dim / p->n_heads;
    int seq_len = pos + 1;
    int n_kv_heads = p->n_kv_heads;
    int kv_mul = p->n_heads / p->n_kv_heads;

    int ratio       = kv_mul;                    // 硬件fanout倍率
    int kv_per_pass  = FSA_NUM_ACTIVE / ratio;   // 一趟读几个唯一KV头
    int num_passes   = p->n_heads / FSA_NUM_ACTIVE;
    int head_bytes   = head_size * sizeof(float);
    int kv_head_bytes = head_size * head_size * (int)sizeof(float); // 单KV头一个tile的字节数

    // KV_STRIDE仍是DDR里每tile物理存储的全部KV头数（n_kv_heads）× 单头tile大小——
    // tile间步长与"单趟读几个头"无关。单趟只靠K_BASE偏移定位起始KV头 + 缩短cmd_len。
    int kv_stride = n_kv_heads * kv_head_bytes;

    float* k_base = s->key_cache + loff;
    float* v_base = s->value_cache + loff;

    // ATTN_SCALE = log2(e) / sqrt(head_size=8) = 1.4426950 / 2.8284271 ≈ 0.5100
    unsigned int scale_bits = 0x3F0293EE;

    for (int pass = 0; pass < num_passes; pass++) {
        // 本趟起始KV头索引 = pass * kv_per_pass；据此在tile内偏移K/V_BASE。
        int kv_start = pass * kv_per_pass;
        unsigned long k_pass = (unsigned long)k_base + (unsigned long)kv_start * kv_head_bytes;
        unsigned long v_pass = (unsigned long)v_base + (unsigned long)kv_start * kv_head_bytes;

        // 准备Q：本趟处理NUM_ACTIVE个连续Q头（pass*NUM_ACTIVE + g）
        for (int g = 0; g < FSA_NUM_ACTIVE; g++) {
            int q_head_idx = pass * FSA_NUM_ACTIVE + g;
            memcpy(fsa_q_buf + g * head_size,
                   s->q + q_head_idx * head_size,
                   head_bytes);
        }

        // 只flush Q和O（KV已在store_kv_to_cache后增量flush过）
        cache_flush(fsa_q_buf, FSA_NUM_ACTIVE * head_bytes);
        cache_flush(fsa_o_buf, FSA_NUM_ACTIVE * head_bytes);

        // 配置FSA CSR
        cb_write(REG_Q_BASE_ADDR, (unsigned long)fsa_q_buf);
        cb_write(REG_K_BASE_ADDR, k_pass);
        cb_write(REG_V_BASE_ADDR, v_pass);
        cb_write(REG_O_BASE_ADDR, (unsigned long)fsa_o_buf);
        cb_write(REG_HEAD_DIM_ADDR, head_size);
        cb_write(REG_SEQ_LEN_ADDR, seq_len);
        cb_write(REG_KV_STRIDE_ADDR, kv_stride);
        // 复活REG_NUM_HEADS承载"本趟唯一KV头数"，硬件据此fanout到NUM_ACTIVE个组
        cb_write(REG_NUM_HEADS_ADDR, kv_per_pass);
        cb_write(REG_ATTN_SCALE_ADDR, scale_bits);

        // 启动FSA模式
        cb_write(REG_CTRL_ADDR, CSR_CTRL_START_BIT | CSR_CTRL_MODE_FSA);
        cpu_idle();
        HWI1_IntrHandler();

        // 读回结果，invalidate cache后拷贝到xb对应位置（组g → Q头pass*NUM_ACTIVE+g）
        cache_flush(fsa_o_buf, FSA_NUM_ACTIVE * head_bytes);
        for (int g = 0; g < FSA_NUM_ACTIVE; g++) {
            int q_head_idx = pass * FSA_NUM_ACTIVE + g;
            memcpy(s->xb + q_head_idx * head_size,
                   fsa_o_buf + g * head_size,
                   head_bytes);
        }
    }
}

// 旧路径：每趟读全部n_kv_heads头（不省带宽但对任意config都正确）。
// 这一趟硬件处理NUM_ACTIVE个Q组、每组各一个独立KV头，故"本趟唯一KV头数"=n_kv_heads
// （legacy触发场景n_kv_heads==NUM_ACTIVE，即MHA、ratio=1、单热bank_we）。硬件不再对
// REG_NUM_HEADS做任何兜底，软件必须显式写值——此处写n_kv_heads。fanout分解条件不满足
// 时退回此路径，行为与改动前逐字节一致。
static void attention_fsa_legacy(RunState* s, Config* p, int pos, int loff) {
    int head_size = p->dim / p->n_heads;
    int seq_len = pos + 1;
    int n_kv_heads = p->n_kv_heads;
    int kv_mul = p->n_heads / p->n_kv_heads;
    int kv_stride = n_kv_heads * head_size * head_size * (int)sizeof(float);

    float* k_base = s->key_cache + loff;
    float* v_base = s->value_cache + loff;
    unsigned int scale_bits = 0x3F0293EE;

    for (int pass = 0; pass < kv_mul; pass++) {
        for (int g = 0; g < n_kv_heads; g++) {
            int q_head_idx = pass + g * kv_mul;
            memcpy(fsa_q_buf + g * head_size,
                   s->q + q_head_idx * head_size,
                   head_size * sizeof(float));
        }
        cache_flush(fsa_q_buf, n_kv_heads * head_size * sizeof(float));
        cache_flush(fsa_o_buf, n_kv_heads * head_size * sizeof(float));

        cb_write(REG_Q_BASE_ADDR, (unsigned long)fsa_q_buf);
        cb_write(REG_K_BASE_ADDR, (unsigned long)k_base);
        cb_write(REG_V_BASE_ADDR, (unsigned long)v_base);
        cb_write(REG_O_BASE_ADDR, (unsigned long)fsa_o_buf);
        cb_write(REG_HEAD_DIM_ADDR, head_size);
        cb_write(REG_SEQ_LEN_ADDR, seq_len);
        cb_write(REG_KV_STRIDE_ADDR, kv_stride);
        // 硬件删除了REG_NUM_HEADS兜底，本寄存器改为FSA启动前必配。legacy一趟读全部
        // n_kv_heads个独立KV头（stories260K下=4=硬件num_active，ratio=1单热），显式写
        // n_kv_heads让硬件行为与改动前逐字节一致。
        cb_write(REG_NUM_HEADS_ADDR, n_kv_heads);
        cb_write(REG_ATTN_SCALE_ADDR, scale_bits);

        cb_write(REG_CTRL_ADDR, CSR_CTRL_START_BIT | CSR_CTRL_MODE_FSA);
        cpu_idle();
        HWI1_IntrHandler();

        cache_flush(fsa_o_buf, n_kv_heads * head_size * sizeof(float));
        for (int g = 0; g < n_kv_heads; g++) {
            int q_head_idx = pass + g * kv_mul;
            memcpy(s->xb + q_head_idx * head_size,
                   fsa_o_buf + g * head_size,
                   head_size * sizeof(float));
        }
    }
}

// fanout快路径的适用条件（全部满足才走attention_fsa_fanout省带宽路径）：
//   1. kv_mul能被NUM_ACTIVE整除（kv_per_pass = NUM_ACTIVE/kv_mul 为正整数，
//      否则一趟覆盖不满/多于4组 → 组错位；也排除kv_mul>NUM_ACTIVE导致kv_per_pass=0）
//   2. n_heads能被NUM_ACTIVE整除（num_passes整数，Q头能按每趟4个整齐切分）
//   3. n_heads >= NUM_ACTIVE（至少跑一趟）
// stories260K(kv_mul=2,n_heads=8)全满足。不满足则退回legacy逐头多趟。
static int fsa_fanout_ok(Config* p) {
    int kv_mul = p->n_heads / p->n_kv_heads;
    if (kv_mul <= 0 || (FSA_NUM_ACTIVE % kv_mul) != 0) return 0;
    if (p->n_heads < FSA_NUM_ACTIVE) return 0;
    if ((p->n_heads % FSA_NUM_ACTIVE) != 0) return 0;
    return 1;
}

static void attention_fsa(RunState* s, Config* p, int pos, int loff) {
    if (fsa_fanout_ok(p))
        attention_fsa_fanout(s, p, pos, loff);   // 省带宽快路径（KV只读一次+硬件fanout）
    else
        attention_fsa_legacy(s, p, pos, loff);    // 通用回退（每趟读全部头，行为=改动前）
}


float* forward(Transformer* transformer, int token, int pos) {

    // a few convenience variables
    Config* p = &transformer->config;
    TransformerWeights* w = &transformer->weights;
    RunState* s = &transformer->state;
    float *x = s->x;
    int dim = p->dim;
    int kv_dim = (p->dim * p->n_kv_heads) / p->n_heads;
    int kv_mul = p->n_heads / p->n_kv_heads; // integer multiplier of the kv heads to the query heads
    int hidden_dim =  p->hidden_dim;
    int head_size = dim / p->n_heads;

    // copy the token embedding into x
    float* content_row = w->token_embedding_table + token * dim;
    memcpy(x, content_row, dim * sizeof(float));

    // forward all the layers
    for(unsigned long long l = 0; l < p->n_layers; l++) {

        // attention rmsnorm
        rmsnorm(s->xb, x, w->rms_att_weight + l*dim, dim);

        // KV cache layer offset（tile-based布局）
        int n_kv_heads = p->n_kv_heads;
        int max_tiles = (p->seq_len + head_size - 1) / head_size;
        int tile_size = n_kv_heads * head_size * head_size;
        int loff = l * max_tiles * tile_size;

        // qkv matmuls for this position
        matmul(s->q, s->xb, w->wq + l*dim*dim, dim, dim);
        matmul(s->k, s->xb, w->wk + l*dim*kv_dim, dim, kv_dim);
        matmul(s->v, s->xb, w->wv + l*dim*kv_dim, dim, kv_dim);

        // RoPE relative positional encoding: complex-valued rotate q and k in each head
        for (int i = 0; i < dim; i+=2) {
            int head_dim = i % head_size;
            float freq = 1.0f / powf(10000.0f, head_dim / (float)head_size);
            float val = pos * freq;
            float fcr = cosf(val);
            float fci = sinf(val);
            int rotn = i < kv_dim ? 2 : 1; // how many vectors? 2 = q & k, 1 = q only
            for (int v = 0; v < rotn; v++) {
                float* vec = v == 0 ? s->q : s->k; // the vector to rotate (query or key)
                float v0 = vec[i];
                float v1 = vec[i+1];
                vec[i]   = v0 * fcr - v1 * fci;
                vec[i+1] = v0 * fci + v1 * fcr;
            }
        }

        // RoPE后将K/V scatter到tile-based cache
        store_kv_to_cache(s->key_cache, loff, pos, s->k, kv_dim, head_size);
        store_kv_to_cache(s->value_cache, loff, pos, s->v, kv_dim, head_size);

        // 增量flush：只flush刚写入的那一行KV数据（每head 8 bytes × 4 heads = 32 bytes × 2）
        {
            int tile_idx = pos / head_size;
            int n_kv_heads = p->n_kv_heads;
            int tile_size = n_kv_heads * head_size * head_size;
            float* k_tile_base = s->key_cache + loff + tile_idx * tile_size;
            float* v_tile_base = s->value_cache + loff + tile_idx * tile_size;
            // flush整个当前tile（最多1024 bytes），确保DMA可见
            cache_flush(k_tile_base, tile_size * sizeof(float));
            cache_flush(v_tile_base, tile_size * sizeof(float));
        }

        // 硬件加速attention（FSA模式）
        attention_fsa(s, p, pos, loff);

#if VERIFY_MATMUL
        // CPU golden attention比对（原版标准实现）
        // 注意：CPU无FPU，expf/sqrtf极慢，pos大时每token验证需数秒
        if (pos > 0) {
            verify_fsa_calls++;
            if ((verify_fsa_calls % 5) == 1)
                printf("[VERIFY_FSA] computing golden pos=%d L%llu...\r", pos, l);
            float xb_golden[64];  // dim=64
            int seq_len = pos + 1;
            float max_err = 0.0f;
            int mismatch = 0;

            for (int h = 0; h < p->n_heads; h++) {
                float* q = s->q + h * head_size;
                float att_buf[256];  // seq_len最大256
                int kv_head = h / kv_mul;

                // QK点积 + scale
                for (int t = 0; t <= pos; t++) {
                    // 从tile-based cache读取K
                    int tile_idx = t / head_size;
                    int row_in_tile = t % head_size;
                    float* k_ptr = s->key_cache + loff
                        + tile_idx * n_kv_heads * head_size * head_size
                        + kv_head * head_size * head_size
                        + row_in_tile * head_size;
                    float score = 0.0f;
                    for (int i = 0; i < head_size; i++)
                        score += q[i] * k_ptr[i];
                    att_buf[t] = score / sqrtf(head_size);
                }

                // softmax
                softmax(att_buf, seq_len);

                // PV加权求和
                float* xb_h = xb_golden + h * head_size;
                memset(xb_h, 0, head_size * sizeof(float));
                for (int t = 0; t <= pos; t++) {
                    int tile_idx = t / head_size;
                    int row_in_tile = t % head_size;
                    float* v_ptr = s->value_cache + loff
                        + tile_idx * n_kv_heads * head_size * head_size
                        + (h / kv_mul) * head_size * head_size
                        + row_in_tile * head_size;
                    for (int i = 0; i < head_size; i++)
                        xb_h[i] += att_buf[t] * v_ptr[i];
                }
            }

            // 比对xb（硬件结果）vs xb_golden（CPU结果）
            // 与TB相同的判定逻辑：近零值用绝对误差，其他用相对误差15%
            for (int i = 0; i < dim; i++) {
                float diff = fabsf(s->xb[i] - xb_golden[i]);
                if (diff > max_err) max_err = diff;
                if (fabsf(xb_golden[i]) < 0.01f) {
                    if (diff > 0.05f) mismatch++;
                } else {
                    float rel = diff / fabsf(xb_golden[i]);
                    if (rel > 0.15f) mismatch++;
                }
            }
            if (l == 0) {
                if (max_err > verify_fsa_global_max_err)
                    verify_fsa_global_max_err = max_err;
                if (mismatch > 0)
                    verify_fsa_mismatch_calls++;
            }
            // 只报告第一层（L0）的误差，排除跨层累积效应
            if (l == 0 && ((verify_fsa_calls % 80) == 0 || (mismatch > 0 && verify_fsa_mismatch_calls <= 3))) {
                printf("[VERIFY_FSA] call#%d L%llu pos=%d max_err=%.4f mismatches=%d\n",
                       verify_fsa_calls, l, pos, max_err, mismatch);
                if (mismatch > 0 && verify_fsa_mismatch_calls <= 3) {
                    for (int dbg = 0; dbg < 4 && dbg < dim; dbg++)
                        printf("  [%d] hw=%.6f golden=%.6f\n", dbg, s->xb[dbg], xb_golden[dbg]);
                }
            }
            // 打印L0和L4的score范围（验证深层score是否更极端）
            if (pos == 5 && (l == 0 || l == 4) && verify_fsa_calls <= 10) {
                float* q0 = s->q;
                float score_min = 1e10f, score_max = -1e10f;
                for (int t = 0; t <= pos; t++) {
                    int tile_idx = t / head_size;
                    int row_in_tile = t % head_size;
                    float* k_ptr = s->key_cache + loff
                        + tile_idx * n_kv_heads * head_size * head_size
                        + row_in_tile * head_size;
                    float score = 0.0f;
                    for (int i = 0; i < head_size; i++)
                        score += q0[i] * k_ptr[i];
                    score /= sqrtf(head_size);
                    if (score < score_min) score_min = score;
                    if (score > score_max) score_max = score;
                }
                printf("[SCORE_DIST] L%llu pos=%d score_range=[%.3f, %.3f] spread=%.3f\n",
                       l, pos, score_min, score_max, score_max - score_min);
                // 打印K[0][0..3]验证KV cache读取正确性
                float* k0_ptr = s->key_cache + loff;
                printf("[KV_CHECK] L%llu K[0][0..3]=%.4f %.4f %.4f %.4f loff=%d\n",
                       l, k0_ptr[0], k0_ptr[1], k0_ptr[2], k0_ptr[3], loff);
                printf("[Q_CHECK] L%llu Q[0..3]=%.4f %.4f %.4f %.4f\n",
                       l, s->q[0], s->q[1], s->q[2], s->q[3]);
            }
        }
#endif

        // final matmul to get the output of the attention
        matmul(s->xb2, s->xb, w->wo + l*dim*dim, dim, dim);

        // residual connection back into x
        for (int i = 0; i < dim; i++) {
            x[i] += s->xb2[i];
        }

        // ffn rmsnorm
        rmsnorm(s->xb, x, w->rms_ffn_weight + l*dim, dim);

        // Now for FFN in PyTorch we have: self.w2(F.silu(self.w1(x)) * self.w3(x))
        // first calculate self.w1(x) and self.w3(x)
        matmul(s->hb, s->xb, w->w1 + l*dim*hidden_dim, dim, hidden_dim);
        matmul(s->hb2, s->xb, w->w3 + l*dim*hidden_dim, dim, hidden_dim);

        // SwiGLU non-linearity
        for (int i = 0; i < hidden_dim; i++) {
            float val = s->hb[i];
            // silu(x)=x*σ(x), where σ(x) is the logistic sigmoid
            val *= (1.0f / (1.0f + expf(-val)));
            // elementwise multiply with w3(x)
            val *= s->hb2[i];
            s->hb[i] = val;
        }

        // final matmul to get the output of the ffn
        matmul(s->xb, s->hb, w->w2 + l*dim*hidden_dim, hidden_dim, dim);

        // residual connection
        for (int i = 0; i < dim; i++) {
            x[i] += s->xb[i];
        }
    }

    // final rmsnorm
    rmsnorm(x, x, w->rms_final_weight, dim);

    // classifier into logits
    matmul(s->logits, x, w->wcls, p->dim, p->vocab_size);
    return s->logits;
}

// ----------------------------------------------------------------------------
// The Byte Pair Encoding (BPE) Tokenizer that translates strings <-> tokens

typedef struct {
    char *str;
    int id;
} TokenIndex;

typedef struct {
    char** vocab;
    float* vocab_scores;
    TokenIndex *sorted_vocab;
    int vocab_size;
    unsigned int max_token_length;
    unsigned char byte_pieces[512]; // stores all single-byte strings
} Tokenizer;

int compare_tokens(const void *a, const void *b) {
    return strcmp(((TokenIndex*)a)->str, ((TokenIndex*)b)->str);
}

void build_tokenizer(Tokenizer* t, int vocab_size) {
    // i should have written the vocab_size into the tokenizer file... sigh
    t->vocab_size = vocab_size;
    // malloc space to hold the scores and the strings
    t->vocab = (char**)malloc(vocab_size * sizeof(char*));
    t->vocab_scores = (float*)malloc(vocab_size * sizeof(float));
    t->sorted_vocab = NULL; // initialized lazily
    for (int i = 0; i < 256; i++) {
        t->byte_pieces[i * 2] = (unsigned char)i;
        t->byte_pieces[i * 2 + 1] = '\0';
    }

    // MODIFICATION: Read tokenizer data from the embedded `tok512_bin` array.
    unsigned char* p_tokenizer_data = tok512_bin;
    unsigned char* end_tokenizer_data = tok512_bin + tok512_bin_len;

    // Read max_token_length
    if (p_tokenizer_data + sizeof(int) > end_tokenizer_data) {
        fprintf(stderr, "Error reading max_token_length: not enough data in tok512_bin\n");
        exit(EXIT_FAILURE);
    }
    memcpy(&t->max_token_length, p_tokenizer_data, sizeof(int));
    p_tokenizer_data += sizeof(int);

    // Read vocab and scores
    for (int i = 0; i < vocab_size; i++) {
        // Read score
        if (p_tokenizer_data + sizeof(float) > end_tokenizer_data) {
            fprintf(stderr, "Error reading vocab_score for token %d: not enough data\n", i);
            exit(EXIT_FAILURE);
        }
        memcpy(t->vocab_scores + i, p_tokenizer_data, sizeof(float));
        p_tokenizer_data += sizeof(float);

        // Read string length
        int len;
        if (p_tokenizer_data + sizeof(int) > end_tokenizer_data) {
            fprintf(stderr, "Error reading length for token %d: not enough data\n", i);
            exit(EXIT_FAILURE);
        }
        memcpy(&len, p_tokenizer_data, sizeof(int));
        p_tokenizer_data += sizeof(int);

        // Read string
        if (len < 0 || p_tokenizer_data + len > end_tokenizer_data) {
             fprintf(stderr, "Error reading vocab string for token %d: invalid length or not enough data (len: %d)\n", i, len);
             exit(EXIT_FAILURE);
        }
        t->vocab[i] = (char *)malloc(len + 1);
        if (!t->vocab[i]) { fprintf(stderr, "malloc failed: t->vocab[%d]\n", i); exit(EXIT_FAILURE); }
        memcpy(t->vocab[i], p_tokenizer_data, len);
        t->vocab[i][len] = '\0';
        p_tokenizer_data += len;
    }
}

void free_tokenizer(Tokenizer* t) {
    for (int i = 0; i < t->vocab_size; i++) { free(t->vocab[i]); }
    free(t->vocab);
    free(t->vocab_scores);
    free(t->sorted_vocab);
}

char* decode(Tokenizer* t, int prev_token, int token) {
    char *piece = t->vocab[token];
    // following BOS (1) token, sentencepiece decoder strips any leading whitespace (see PR #89)
    if (prev_token == 1 && piece[0] == ' ') { piece++; }
    // careful, some tokens designate raw bytes, and look like e.g. '<0x01>'
    // parse this and convert and return the actual byte
    unsigned char byte_val;
    if (sscanf(piece, "<0x%02hhX>", &byte_val) == 1) {
        piece = (char*)t->byte_pieces + byte_val * 2;
    }
    return piece;
}

void safe_printf(char *piece) {
    // piece might be a raw byte token, and we only want to print printable chars or whitespace
    // because some of the other bytes can be various control codes, backspace, etc.
    if (piece == NULL) { return; }
    if (piece[0] == '\0') { return; }
    if (piece[1] == '\0') {
        unsigned char byte_val = piece[0];
        if (!(isprint(byte_val) || isspace(byte_val))) {
            return; // bad byte, don't print it
        }
    }
    printf("%s", piece);
}

int str_lookup(char *str, TokenIndex *sorted_vocab, int vocab_size) {
    // efficiently find the perfect match for str in vocab, return its index or -1 if not found
    TokenIndex tok = { .str = str }; // acts as the key to search for
    TokenIndex *res = bsearch(&tok, sorted_vocab, vocab_size, sizeof(TokenIndex), compare_tokens);
    return res != NULL ? res->id : -1;
}

void encode(Tokenizer* t, char *text, int8_t bos, int8_t eos, int *tokens, int *n_tokens) {
    // encode the string text (input) into an upper-bound preallocated tokens[] array
    // bos != 0 means prepend the BOS token (=1), eos != 0 means append the EOS token (=2)
    if (text == NULL) { fprintf(stderr, "cannot encode NULL text\n"); exit(EXIT_FAILURE); }

    if (t->sorted_vocab == NULL) {
        // lazily malloc and sort the vocabulary
        t->sorted_vocab = malloc(t->vocab_size * sizeof(TokenIndex));
        for (int i = 0; i < t->vocab_size; i++) {
            t->sorted_vocab[i].str = t->vocab[i];
            t->sorted_vocab[i].id = i;
        }
        qsort(t->sorted_vocab, t->vocab_size, sizeof(TokenIndex), compare_tokens);
    }

    // create a temporary buffer that will store merge candidates of always two consecutive tokens
    // *2 for concat, +1 for null terminator +2 for UTF8 (in case max_token_length is 1)
    char* str_buffer = malloc((t->max_token_length*2 +1 +2) * sizeof(char));
    size_t str_len = 0;

    // start at 0 tokens
    *n_tokens = 0;

    // add optional BOS (=1) token, if desired
    if (bos) tokens[(*n_tokens)++] = 1;

    // add_dummy_prefix is true by default
    // so prepend a dummy prefix token to the input string, but only if text != ""
    // TODO: pretty sure this isn't correct in the general case but I don't have the
    // energy to read more of the sentencepiece code to figure out what it's doing
    if (text[0] != '\0') {
        int dummy_prefix = str_lookup(" ", t->sorted_vocab, t->vocab_size);
        if (dummy_prefix != -1) {
            tokens[(*n_tokens)++] = dummy_prefix;
        }
    }

    // process the raw (UTF-8) byte sequence of the input string
    for (char *p = text; *p != '\0';) {
        int id = -1;
        size_t len = 0;
        for (int i = 1; i <= t->max_token_length && p[i-1] != '\0'; i++) {
            memcpy(str_buffer, p, i);
            str_buffer[i] = '\0';
            int current_id = str_lookup(str_buffer, t->sorted_vocab, t->vocab_size);
            if (current_id != -1) {
                // we found a match in the vocab
                id = current_id;
                len = i;
            }
        }

        if (id != -1) {
            // we found a match, add it to the tokens and advance
            tokens[(*n_tokens)++] = id;
            p += len;
        } else {
            // we did not find any match in the vocab, fall back to byte-level token
            tokens[(*n_tokens)++] = (unsigned char)(*p) + 3;
            p++;
        }
    }

    // merge the best consecutive pair each iteration, according the scores in vocab_scores
    while (1) {
        float best_score = -1e10;
        int best_id = -1;
        int best_idx = -1;

        for (int i=0; i < (*n_tokens-1); i++) {
            // check if we can merge the pair (tokens[i], tokens[i+1])
            sprintf(str_buffer, "%s%s", t->vocab[tokens[i]], t->vocab[tokens[i+1]]);
            int id = str_lookup(str_buffer, t->sorted_vocab, t->vocab_size);
            if (id != -1 && t->vocab_scores[id] > best_score) {
                // this merge pair exists in vocab! record its score and position
                best_score = t->vocab_scores[id];
                best_id = id;
                best_idx = i;
            }
        }

        if (best_idx == -1) {
            break; // we couldn't find any more pairs to merge, so we're done
        }

        // merge the consecutive pair (best_idx, best_idx+1) into new token best_id
        tokens[best_idx] = best_id;
        // delete token at position best_idx+1, shift the entire sequence back 1
        for (int i = best_idx+1; i < (*n_tokens-1); i++) {
            tokens[i] = tokens[i+1];
        }
        (*n_tokens)--; // token length decreased
    }

    // add optional EOS (=2) token, if desired
    if (eos) tokens[(*n_tokens)++] = 2;

    free(str_buffer);
}

// ----------------------------------------------------------------------------
// The Sampler, which takes logits and returns a sampled token
// sampling can be done in a few ways: greedy argmax, sampling, top-p sampling

typedef struct {
    float prob;
    int index;
} ProbIndex; // struct used when sorting probabilities during top-p sampling

typedef struct {
    int vocab_size;
    ProbIndex* probindex; // buffer used in top-p sampling
    float temperature;
    float topp;
    unsigned long long rng_state;
} Sampler;

int sample_argmax(float* probabilities, int n) {
    // return the index that has the highest probability
    int max_i = 0;
    float max_p = probabilities[0];
    for (int i = 1; i < n; i++) {
        if (probabilities[i] > max_p) {
            max_i = i;
            max_p = probabilities[i];
        }
    }
    return max_i;
}

int sample_mult(float* probabilities, int n, float coin) {
    // sample index from probabilities (they must sum to 1!)
    // coin is a random number in [0, 1), usually from random_f32()
    float cdf = 0.0f;
    for (int i = 0; i < n; i++) {
        cdf += probabilities[i];
        if (coin < cdf) {
            return i;
        }
    }
    return n - 1; // in case of rounding errors
}

int compare(const void* a, const void* b) {
    ProbIndex* a_ = (ProbIndex*) a;
    ProbIndex* b_ = (ProbIndex*) b;
    if (a_->prob > b_->prob) return -1;
    if (a_->prob < b_->prob) return 1;
    return 0;
}

int sample_topp(float* probabilities, int n, float topp, ProbIndex* probindex, float coin) {
    // top-p sampling (or "nucleus sampling") samples from the smallest set of
    // tokens that exceed probability topp. This way we never sample tokens that
    // have very low probabilities and are less likely to go "off the rails".
    // coin is a random number in [0, 1), usually from random_f32()

    int n0 = 0;
    // quicksort indices in descending order of probabilities
    // values smaller than (1 - topp) / (n - 1) cannot be part of the result
    // so for efficiency we crop these out as candidates before sorting
    const float cutoff = (1.0f - topp) / (n - 1);
    for (int i = 0; i < n; i++) {
        if (probabilities[i] >= cutoff) {
            probindex[n0].index = i;
            probindex[n0].prob = probabilities[i];
            n0++;
        }
    }
    qsort(probindex, n0, sizeof(ProbIndex), compare);

    // truncate the list where cumulative probability exceeds topp
    float cumulative_prob = 0.0f;
    int last_idx = n0 - 1; // in case of rounding errors consider all elements
    for (int i = 0; i < n0; i++) {
        cumulative_prob += probindex[i].prob;
        if (cumulative_prob > topp) {
            last_idx = i;
            break; // we've exceeded topp by including last_idx
        }
    }

    // sample from the truncated list
    float r = coin * cumulative_prob;
    float cdf = 0.0f;
    for (int i = 0; i <= last_idx; i++) {
        cdf += probindex[i].prob;
        if (r < cdf) {
            return probindex[i].index;
        }
    }
    return probindex[last_idx].index; // in case of rounding errors
}

void build_sampler(Sampler* sampler, int vocab_size, float temperature, float topp, unsigned long long rng_seed) {
    sampler->vocab_size = vocab_size;
    sampler->temperature = temperature;
    sampler->topp = topp;
    sampler->rng_state = rng_seed;
    // buffer only used with nucleus sampling; may not need but it's ~small
    sampler->probindex = malloc(sampler->vocab_size * sizeof(ProbIndex));
}

void free_sampler(Sampler* sampler) {
    free(sampler->probindex);
}

unsigned int random_u32(unsigned long long *state) {
    // xorshift rng: https://en.wikipedia.org/wiki/Xorshift#xorshift.2A
    *state ^= *state >> 12;
    *state ^= *state << 25;
    *state ^= *state >> 27;
    return (*state * 0x2545F4914F6CDD1Dull) >> 32;
}
float random_f32(unsigned long long *state) { // random float32 in [0,1)
    return (random_u32(state) >> 8) / 16777216.0f;
}

int sample(Sampler* sampler, float* logits) {
    // sample the token given the logits and some hyperparameters
    int next;
    if (sampler->temperature == 0.0f) {
        // greedy argmax sampling: take the token with the highest probability
        next = sample_argmax(logits, sampler->vocab_size);
    } else {
        // apply the temperature to the logits
        for (int q=0; q<sampler->vocab_size; q++) { logits[q] /= sampler->temperature; }
        // apply softmax to the logits to get the probabilities for next token
        softmax(logits, sampler->vocab_size);
        // flip a (float) coin (this is our source of entropy for sampling)
        float coin = random_f32(&sampler->rng_state);
        // we sample from this distribution to get the next token
        if (sampler->topp <= 0 || sampler->topp >= 1) {
            // simply sample from the predicted probability distribution
            next = sample_mult(logits, sampler->vocab_size, coin);
        } else {
            // top-p (nucleus) sampling, clamping the least likely tokens to zero
            next = sample_topp(logits, sampler->vocab_size, sampler->topp, sampler->probindex, coin);
        }
    }
    return next;
}

// ----------------------------------------------------------------------------
// utilities: time

// long time_in_ms() {
//     // return time in milliseconds, for benchmarking the model speed
//     struct timespec time;
//     clock_gettime(CLOCK_REALTIME, &time);
//     return time.tv_sec * 1000 + time.tv_nsec / 1000000;
// }

// ----------------------------------------------------------------------------
// generation loop

void generate(Transformer *transformer, Tokenizer *tokenizer, Sampler *sampler, char *prompt, int steps) {
    char *empty_prompt = "";
    if (prompt == NULL) { prompt = empty_prompt; }

    // encode the (string) prompt into tokens sequence
    int num_prompt_tokens = 0;
    int* prompt_tokens = (int*)malloc((strlen(prompt)+3) * sizeof(int)); // +3 for '\0', ?BOS, ?EOS
    encode(tokenizer, prompt, 1, 0, prompt_tokens, &num_prompt_tokens);
    if (num_prompt_tokens < 1) {
        fprintf(stderr, "something is wrong, expected at least 1 prompt token\n");
        exit(EXIT_FAILURE);
    }

    // start the main loop
    unsigned long start_cycles = get_cpu_clock_count();
    unsigned long last_report_cycles = start_cycles;
    int emitted_tokens = 0;
    int next;        // will store the next token in the sequence
    int token = prompt_tokens[0]; // kick off with the first token in the prompt
    int pos = 0;     // position in the sequence
    while (pos < steps) {

        // forward the transformer to get logits for the next token
        float* logits = forward(transformer, token, pos);

        // advance the state machine
        if (pos < num_prompt_tokens - 1) {
            // if we are still processing the input prompt, force the next prompt token
            next = prompt_tokens[pos + 1];
        } else {
            // otherwise sample the next token from the logits
            next = sample(sampler, logits);
        }
        pos++;

        // data-dependent terminating condition: the BOS (=1) token delimits sequences
        if (next == 1) { break; }

        // print the token as string, decode it with the Tokenizer object
        char* piece = decode(tokenizer, token, next);
        safe_printf(piece); // same as printf("%s", piece), but skips "unsafe" bytes
        fflush(stdout);
        token = next;
        emitted_tokens++;

#if BENCH_TOKEN_REPORT_INTERVAL > 0
        if ((emitted_tokens % BENCH_TOKEN_REPORT_INTERVAL) == 0) {
            unsigned long now_cycles = get_cpu_clock_count();
            printf("\n[BENCH] generate_progress emitted=%d delta_cycles=%lu total_cycles=%lu\n",
                   emitted_tokens,
                   now_cycles - last_report_cycles,
                   now_cycles - start_cycles);
            last_report_cycles = now_cycles;
        }
#endif

        // init the timer here because the first iteration can be slower
        // if (start == 0) { start = time_in_ms(); }
    }
    printf("\n");

    {
        unsigned long end_cycles = get_cpu_clock_count();
        unsigned long total_cycles = end_cycles - start_cycles;
        unsigned long cycles_per_token = emitted_tokens > 0 ? (total_cycles / (unsigned long)emitted_tokens) : 0;
        printf("[BENCH] generate_done emitted=%d cycles=%lu cycles_per_token=%lu\n",
               emitted_tokens, total_cycles, cycles_per_token);
        if (bench_matmul_calls > 0) {
            unsigned long long avg_matmul = bench_matmul_cycles_total / bench_matmul_calls;
            printf("[BENCH] matmul_done calls=%llu total_cycles=%llu avg_cycles=%llu\n",
                   bench_matmul_calls, bench_matmul_cycles_total, avg_matmul);
        }
    }

    // report achieved tok/s (pos-1 because the timer starts after first iteration)
    // if (pos > 1) {
    //     long end = time_in_ms();
    //     fprintf(stderr, "achieved tok/s: %f\n", (pos-1) / (double)(end-start)*1000);
    // }

    free(prompt_tokens);
}

void read_stdin(const char* guide, char* buffer, size_t bufsize) {
    // 裸机直接从UART读取一行（不依赖fgets/stdin）
    printf("%s\n", guide);  // 加\n确保提示立即刷出（行缓冲下无\n不显示）

    extern unsigned char uart_getchar(void);
    size_t i = 0;
    while (i < bufsize - 1) {
        unsigned char c = uart_getchar();
        if (c == '\r' || c == '\n') {
            printf("\r\n");
            break;
        }
        if (c == 0x7f || c == '\b') {  // 退格处理
            if (i > 0) { i--; printf("\b \b"); }
            continue;
        }
        buffer[i++] = c;
        printf("%c", c);  // 回显
    }
    buffer[i] = '\0';
}

// ----------------------------------------------------------------------------
// chat loop
// I manually inspected the tokens for a few chat conversations compared to
// python reference and that seemed ok, but this was not thoroughly tested and
// is not safely implemented, it's more a proof of concept atm.

void chat(Transformer *transformer, Tokenizer *tokenizer, Sampler *sampler,
          char *cli_user_prompt, char *cli_system_prompt, int steps) {

    // buffer for reading the user prompt from stdin（续写demo只需一个输入缓冲）
    char user_prompt[512];
    char rendered_prompt[1152];
    int num_prompt_tokens = 0;
    int* prompt_tokens = (int*)malloc(1152 * sizeof(int));
    int user_idx;

    // start the main loop
    int8_t user_turn = 1; // user starts
    int next;        // will store the next token in the sequence
    int token;       // stores the current token to feed into the transformer
    int prev_token;
    int pos = 0;     // position in the sequence
    while (pos < steps) {

        // when it is the user's turn to contribute tokens to the dialog...
        if (user_turn) {
            // 续写demo：直接把用户输入当作故事开头prompt，不套[INST]对话模板。
            // stories260K是"续写故事"模型，没学过对话格式，[INST]标记会带偏它；
            // 去掉模板后，用户输入的文字直接作为prompt交给模型接着往下写。
            if (pos == 0 && cli_user_prompt != NULL) {
                // 若命令行传入了prompt则直接用
                strcpy(user_prompt, cli_user_prompt);
            } else {
                // 否则从串口读一行作为续写开头
                read_stdin("Prompt: ", user_prompt, sizeof(user_prompt));
            }
            // 用户输入即prompt原文，不加任何模板包裹
            strcpy(rendered_prompt, user_prompt);
            // encode the rendered prompt into tokens
            encode(tokenizer, rendered_prompt, 1, 0, prompt_tokens, &num_prompt_tokens);
            user_idx = 0; // reset the user index
            user_turn = 0;
            printf("Story: ");
        }

        // determine the token to pass into the transformer next
        if (user_idx < num_prompt_tokens) {
            // if we are still processing the input prompt, force the next prompt token
            token = prompt_tokens[user_idx++];
        } else {
            // otherwise use the next token sampled from previous turn
            token = next;
        }
        // EOS (=2) token ends the Assistant turn
        if (token == 2) { user_turn = 1; }

        // forward the transformer to get logits for the next token
        float* logits = forward(transformer, token, pos);
        next = sample(sampler, logits);
        pos++;

        if (user_idx >= num_prompt_tokens && next != 2) {
            // the Assistant is responding, so print its output
            char* piece = decode(tokenizer, token, next);
            safe_printf(piece); // same as printf("%s", piece), but skips "unsafe" bytes
            fflush(stdout);
        }
        if (next == 2) { printf("\n"); }
    }
    printf("\n");
    free(prompt_tokens);
}


// ----------------------------------------------------------------------------
// CLI, include only if not testing
#ifndef TESTING

void error_usage() {
    fprintf(stderr, "Usage:   run [options]\n");
    fprintf(stderr, "Example: run -n 256 -i \"Once upon a time\"\n");
    fprintf(stderr, "Options:\n");
    fprintf(stderr, "  -t <float>  temperature in [0,inf], default 1.0\n");
    fprintf(stderr, "  -p <float>  p value in top-p (nucleus) sampling in [0,1] default 0.9\n");
    fprintf(stderr, "  -s <int>    random seed, default time(NULL)\n");
    fprintf(stderr, "  -n <int>    number of steps to run for, default 256. 0 = max_seq_len\n");
    fprintf(stderr, "  -i <string> input prompt\n");
    fprintf(stderr, "  -m <string> mode: generate|chat, default: generate\n");
    fprintf(stderr, "  -y <string> (optional) system prompt in chat mode\n");
    exit(EXIT_FAILURE);
}

int main(int argc, char *argv[]) {

    // default parameters
    // temperature=0.0f → greedy argmax(确定性输出)：每步取概率最大的token，
    // 输出最连贯、可复现。stories260K是玩具模型，greedy下generate能跑出通顺故事；
    // 若想要随机性可改回1.0f(会走top-p采样，输出发散)。
    float temperature = 0.0f;
    float topp = 0.9f;
    int steps = 256;
    char *prompt = NULL;
    unsigned long long rng_seed = 0;
    char *mode = "generate";
    char *system_prompt = NULL;

    // poor man's C argparse
    for (int i = 1; i < argc; i+=2) {
        // must have a value after i
        if (i + 1 >= argc) { error_usage(); }
        if (argv[i][0] != '-') { error_usage(); }
        if (strlen(argv[i]) != 2) { error_usage(); }
        // read in the args
        if (argv[i][1] == 't') { temperature = atof(argv[i + 1]); }
        else if (argv[i][1] == 'p') { topp = atof(argv[i + 1]); }
        else if (argv[i][1] == 's') { rng_seed = atoi(argv[i + 1]); }
        else if (argv[i][1] == 'n') { steps = atoi(argv[i + 1]); }
        else if (argv[i][1] == 'i') { prompt = argv[i + 1]; }
        else if (argv[i][1] == 'm') { mode = argv[i + 1]; }
        else if (argv[i][1] == 'y') { system_prompt = argv[i + 1]; }
        else { error_usage(); }
    }

    // parameter validation/overrides
    if (rng_seed <= 0) rng_seed = (unsigned int)RegRead(RANDOM_BASE);
    // 裸机无命令行参数，temperature/topp/steps恒为默认值1.0f/0.9f/256，
    // 下面三行clamp判断永远不触发，是从llama2.c命令行版移植来的死代码；
    // 且GCC(-mabi=ilp32f)会把它们优化成fsel(浮点条件选择)指令——当前硬件
    // 解码器尚未支持fsel，执行到即死循环卡死。裸机场景直接注释掉。
    // if (temperature < 0.0) temperature = 0.0;
    // if (topp < 0.0 || 1.0 < topp) topp = 0.9;
    // if (steps < 0) steps = 0;

    // 裸机模式选择：拨码开关bit0=1时进入chat模式，否则generate
#if !SIMU
    unsigned long sw = RegRead(SWITCH_BASE);
    if (sw & 0x1) {
        mode = "chat";  // 拨码开关bit0=1进入chat模式
    }
#endif
    printf("[INFO] mode=%s matmul=%s steps=%d\n", mode, CPU_ONLY_MATMUL ? "cpu" : "hw", steps);

    // build the Transformer via the model .bin file
    Transformer transformer;
    unsigned long phase_begin = get_cpu_clock_count();
    build_transformer(&transformer);
    printf("[BENCH] phase_build_transformer cycles=%lu\n", get_cpu_clock_count() - phase_begin);
    if (steps == 0 || steps > transformer.config.seq_len) steps = transformer.config.seq_len;

    // build the Tokenizer via the tokenizer .bin file
    Tokenizer tokenizer;
    phase_begin = get_cpu_clock_count();
    build_tokenizer(&tokenizer, transformer.config.vocab_size);
    printf("[BENCH] phase_build_tokenizer cycles=%lu\n", get_cpu_clock_count() - phase_begin);

    // build the Sampler
    Sampler sampler;
    phase_begin = get_cpu_clock_count();
    build_sampler(&sampler, transformer.config.vocab_size, temperature, topp, rng_seed);
    printf("[BENCH] phase_build_sampler cycles=%lu\n", get_cpu_clock_count() - phase_begin);

    // run!
    phase_begin = get_cpu_clock_count();
    if (strcmp(mode, "generate") == 0) {
        generate(&transformer, &tokenizer, &sampler, prompt, steps);
    } else if (strcmp(mode, "chat") == 0) {
        chat(&transformer, &tokenizer, &sampler, prompt, system_prompt, steps);
    } else {
        fprintf(stderr, "unknown mode: %s\n", mode);
        error_usage();
    }
    printf("[BENCH] phase_run cycles=%lu\n", get_cpu_clock_count() - phase_begin);

    // memory and file handles cleanup
#if VERIFY_MATMUL
    printf("\n========== VERIFY MATMUL SUMMARY ==========\n");
    printf("Total calls:      %d\n", verify_total_calls);
    printf("Failed calls:     %d / %d\n", verify_mismatch_calls, verify_total_calls);
    printf("Total elements:   %d\n", verify_total_elements);
    printf("Total mismatches: %d (threshold=1e-2)\n", verify_total_mismatches);
    printf("Global max_err:   %.6f\n", verify_global_max_err);
    printf("Average err:      %.8f\n", verify_total_elements > 0 ? (float)(verify_err_sum / verify_total_elements) : 0.0f);
    if (verify_n_bucket_cnt > 0) {
        printf("Fail distribution by n:\n");
        for (int i = 0; i < verify_n_bucket_cnt; i++)
            printf("  n=%d: %d fails\n", verify_fail_n_vals[i], verify_fail_by_n[i]);
    }
    if (verify_mismatch_calls == 0)
        printf("MATMUL RESULT: ALL PASS\n");
    else
        printf("MATMUL RESULT: FAIL\n");
    printf("\n========== VERIFY FSA ATTENTION SUMMARY ====\n");
    printf("Total calls:      %d\n", verify_fsa_calls);
    printf("Failed calls:     %d / %d\n", verify_fsa_mismatch_calls, verify_fsa_calls);
    printf("Global max_err:   %.6f\n", verify_fsa_global_max_err);
    if (verify_fsa_mismatch_calls == 0)
        printf("FSA RESULT: ALL PASS\n");
    else
        printf("FSA RESULT: FAIL\n");
    printf("============================================\n");
#endif
    free_sampler(&sampler);
    free_tokenizer(&tokenizer);
    free_transformer(&transformer);
    return 0;
}
#endif
