// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module CMP(
  input         clock,
                rst_n,
                io_d_input_bits_sign,
  input  [7:0]  io_d_input_bits_exp,
  input  [22:0] io_d_input_bits_mantissa,
  output        io_d_output_valid,
                io_d_output_bits_sign,
  output [7:0]  io_d_output_bits_exp,
  output [22:0] io_d_output_bits_mantissa,
  input         io_in_ctrl_valid,
  input  [2:0]  io_in_ctrl_bits_cmd,
  input  [7:0]  io_in_ctrl_bits_causalCounter,
  output        io_out_ctrl_valid,
  output [2:0]  io_out_ctrl_bits_cmd,
  output [7:0]  io_out_ctrl_bits_causalCounter
);

  wire             cmp_max_sign;
  wire [7:0]       cmp_max_exp;
  wire [22:0]      cmp_max_mantissa;
  wire             cmp_diff_sign;
  wire [7:0]       cmp_diff_exp;
  wire [22:0]      cmp_diff_mantissa;
  wire [7:0][22:0] exp2_mantissa_lut =
    '{23'h5CAE0F,
      23'h640507,
      23'h6AE156,
      23'h711D65,
      23'h768DCF,
      23'h7B00A2,
      23'h7E3C91,
      23'h0};
  wire [7:0][7:0]  exp2_exp_lut = '{8'hE, 8'hC, 8'hA, 8'h8, 8'h6, 8'h4, 8'h2, 8'h1};
  reg              oldMax_sign;
  reg  [7:0]       oldMax_exp;
  reg  [22:0]      oldMax_mantissa;
  reg              newMax_sign;
  reg  [7:0]       newMax_exp;
  reg  [22:0]      newMax_mantissa;
  wire             update_new_max = io_in_ctrl_bits_cmd == 3'h0;
  wire             prop_new_max = io_in_ctrl_bits_cmd == 3'h1;
  wire             prop_zero = io_in_ctrl_bits_cmd == 3'h3;
  wire             prop_exp2_intercepts = io_in_ctrl_bits_cmd == 3'h5;
  wire             causal_counter_is_zero =
    io_in_ctrl_bits_causalCounter == 8'h0;
  wire             d_input_sign =
    ~causal_counter_is_zero | io_d_input_bits_sign;
  wire [7:0]       d_input_exp =
    causal_counter_is_zero ? io_d_input_bits_exp : 8'hFF;
  wire [22:0]      d_input_mantissa =
    causal_counter_is_zero ? io_d_input_bits_mantissa : 23'h0;
  reg  [2:0]       exp2_counter_value;
  wire             bypass_normal_diff = prop_zero | prop_exp2_intercepts;
  always @(posedge clock) begin
    if (!rst_n) begin
      oldMax_sign <= 1'h1;
      oldMax_exp <= 8'hFF;
      oldMax_mantissa <= 23'h0;
      newMax_sign <= 1'h1;
      newMax_exp <= 8'hFF;
      newMax_mantissa <= 23'h0;
      exp2_counter_value <= 3'h0;
    end
    else begin
      if (io_in_ctrl_valid) begin
        automatic logic do_reset = io_in_ctrl_bits_cmd == 3'h4;
        automatic logic hold_old_max;
        hold_old_max = bypass_normal_diff | io_in_ctrl_bits_cmd != 3'h2;
        oldMax_sign <= do_reset | (hold_old_max ? oldMax_sign : cmp_max_sign);
        if (do_reset) begin
          oldMax_exp <= 8'hFF;
          oldMax_mantissa <= 23'h0;
          newMax_exp <= 8'hFF;
          newMax_mantissa <= 23'h0;
        end
        else begin
          if (hold_old_max) begin
          end
          else begin
            oldMax_exp <= cmp_max_exp;
            oldMax_mantissa <= cmp_max_mantissa;
          end
          if (~bypass_normal_diff) begin
            newMax_exp <= cmp_max_exp;
            newMax_mantissa <= cmp_max_mantissa;
          end
        end
        newMax_sign <= do_reset | (bypass_normal_diff ? newMax_sign : cmp_max_sign);
      end
      if (io_in_ctrl_valid & prop_exp2_intercepts)
        exp2_counter_value <= exp2_counter_value + 3'h1;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      automatic logic [31:0] _RANDOM[0:2];
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        oldMax_sign = _RANDOM[2'h0][0];
        oldMax_exp = _RANDOM[2'h0][8:1];
        oldMax_mantissa = _RANDOM[2'h0][31:9];
        newMax_sign = _RANDOM[2'h1][0];
        newMax_exp = _RANDOM[2'h1][8:1];
        newMax_mantissa = _RANDOM[2'h1][31:9];
        exp2_counter_value = _RANDOM[2'h2][2:0];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  FPCmpUnit cmpUnit (
    .io_in_a_sign         (update_new_max ? d_input_sign : ~prop_new_max & oldMax_sign),
    .io_in_a_exp
      (update_new_max ? d_input_exp : prop_new_max ? 8'h0 : oldMax_exp),
    .io_in_a_mantissa
      (update_new_max ? d_input_mantissa : prop_new_max ? 23'h0 : oldMax_mantissa),
    .io_in_b_sign         (newMax_sign),
    .io_in_b_exp          (newMax_exp),
    .io_in_b_mantissa     (newMax_mantissa),
    .io_out_max_sign      (cmp_max_sign),
    .io_out_max_exp       (cmp_max_exp),
    .io_out_max_mantissa  (cmp_max_mantissa),
    .io_out_diff_sign     (cmp_diff_sign),
    .io_out_diff_exp      (cmp_diff_exp),
    .io_out_diff_mantissa (cmp_diff_mantissa)
  );
  assign io_d_output_valid = io_in_ctrl_valid & io_in_ctrl_bits_cmd != 3'h4;
  assign io_d_output_bits_sign =
    ~bypass_normal_diff & (update_new_max ? d_input_sign : cmp_diff_sign);
  assign io_d_output_bits_exp =
    prop_zero
      ? 8'h0
      : prop_exp2_intercepts
          ? exp2_exp_lut[exp2_counter_value]
          : update_new_max ? d_input_exp : cmp_diff_exp;
  assign io_d_output_bits_mantissa =
    prop_zero
      ? 23'h0
      : prop_exp2_intercepts
          ? exp2_mantissa_lut[exp2_counter_value]
          : update_new_max ? d_input_mantissa : cmp_diff_mantissa;
  assign io_out_ctrl_valid = io_in_ctrl_valid;
  assign io_out_ctrl_bits_cmd = io_in_ctrl_bits_cmd;
  assign io_out_ctrl_bits_causalCounter =
    causal_counter_is_zero ? 8'h0 : io_in_ctrl_bits_causalCounter - 8'h1;
endmodule

