/*
 * Inference for Llama-2 Transformer model in pure C (No Quantization).
 *
 * This version is adapted for bare-metal execution. All model and tokenizer data
 * is embedded directly into the executable using header files generated by `xxd`.
 * This removes the dependency on a filesystem for loading data.
 *
 * Key Modifications:
 * 1.  Inclusion of `stories_data.h` and `tok512.h` which contain the model
 * and tokenizer data as C arrays.
 * 2.  All quantization-related logic (`QuantizedTensor`, `quantize`, `dequantize`, etc.)
 * has been removed. The model now operates directly on float32 weights.
 * 3.  `build_transformer` and `build_tokenizer` are modified to read from these
 * in-memory arrays instead of from files.
 * 4.  `free_transformer` is adjusted to not free the main data pointer, as it
 * now points to static data in the executable's data segment.
 * 5.  Command-line argument parsing for file paths has been removed.
 * 6.  Global variables for Board Support Package (BSP) are included for
 * hardware-specific configurations (e.g., UART, timers).
 */

#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <stdint.h>
#include <time.h>
#include <math.h>
#include <string.h>
#include <malloc.h>
#if defined _WIN32
    #include "win.h"
#else
    #include <unistd.h>
#endif

// ----------------------------------------------------------------------------
// Board Support Package (BSP) Globals for Bare-Metal Target
// These variables would be configured for the specific hardware.
unsigned long UART_BASE = 0xbf000000;              // UART16550的虚地址
unsigned long CB_BASE = 0xbf300000;
unsigned long CONFREG_TIMER_BASE = 0xbf20f100;      // CONFREG计数器的虚地址
unsigned long CONFREG_CLOCKS_PER_SEC = 50000000L;   // CONFREG时钟频率 (44.286MHz)
unsigned long CORE_CLOCKS_PER_SEC = 33000000L;      // 处理器核时钟频率
unsigned long RANDOM_BASE = 0x1f20f600;
unsigned long SWITCH_BASE = 0x1f20f400;

// ----------------------------------------------------------------------------
// Embedded Data Headers
// These files are generated by a tool like `xxd -i model.bin > model.h`.
// They contain the raw model and tokenizer data as C arrays.
#include "stories_data.h" // Defines stories_bin[] and stories_bin_len
#include "tok512.h"       // Defines tok512_bin[] and tok512_bin_len
#include "hw_accelerator.h" // Hardware accelerator definitions
#include "common_func.h"
#include "confreg_time.h"
#include "bench_profile.h"  // 时间拆解（BENCH=1开启，关闭时零开销）

// ----------------------------------------------------------------------------

// 下面几处 LoongArch 内联汇编都用 __loongarch__ 守卫：交叉编译时行为完全不变，
// x86 host 上则退化成空实现，好让这份 run.c 能原样编成本地可执行文件——用来离线
// 抓真实激活值分布（评估硬件算子近似方案的精度），不必上板。
/* 诊断开关（Makefile NO_IDLE=1）：把等加速器的方式从停机指令换成自旋。
 *
 * 为什么要有它：上板隔离实验出了一个很干净的 2×2 ——
 *   cpu(软浮点,无加速器)=对   cpu_fpu(硬FPU,无加速器)=对
 *   hw (软浮点,有加速器)=对   hw_fpu (硬FPU,有加速器)=**错**
 * 四块单独都对，只有同时具备才错。而 `idle 0` 会挂起整条流水线，本项目的 FPU
 * 又是后加的、异步写回带记分板的独立单元——"停机时还有 FP 操作在途"正好是
 * 只有右下角那一格才会出现的状态。
 *
 * 这个开关只改 `idle 0` 这一件事：中断照发、ISR 照跑、其余全不动，
 * 是单变量对照。**不用轮询 REG_STATUS**——软件里 cb_read 从来没被调用过，
 * 改成轮询会新引入"CSR 读通路"这个变量，万一读通路本身有问题就白测了。 */
static volatile int hwi1_flag;

#if IDLE_WAKECNT
/* 见 cpu_idle 里的说明：三个计数器分别对应 0 圈 / >1 圈 / 总等待次数 */
static unsigned long idle_wake_zero, idle_wake_extra, idle_wait_total;
/* 假唤醒现场：前 8 次的 ESTAT / CRMD 快照 */
static unsigned long idle_samp_estat[8], idle_samp_crmd[8];
static int           idle_samp_n;
#endif

/* ISR 的实体动作：清加速器的中断状态。手工应答处也调它。 */
static inline void hwi1_ack(void)
{
    RegWrite(CB_BASE + REG_CTRL_ADDR, 0);
}

/* 启动加速器之前必须调它：把完成标志清掉，否则谓词循环会被上一次的残留放行。 */
static inline void hw_arm(void)
{
    hwi1_flag = 0;
}

/* 等加速器完成。必须是"循环里复查完成标志"，不能裸用一次 `idle 0` 就往下读，
 * 两条理由：
 *
 * 1) `idle` 醒来 ≠ 我的设备完成。CPU 的 `idle_lock` 由 `has_int` 电平清除
 *    (if_stage.v:180)，而 `has_int` 是**所有使能中断线**的或——`start.S:153` 把
 *    `ecfg` 写成 0x1fff，13 条线全开着。所以 `idle` 返回只说明"IF 级看到了某个
 *    使能的中断条件"。
 *    更糟的是 `has_int` 还有第二个消费者：`id_stage.v:1331` 要**指令走到 ID 级**
 *    时它仍然为真，中断才真被取走。一拍宽的电平足以在 IF 级清掉 idle_lock，
 *    却撑不到指令进 ID —— 于是 CPU 醒了、ISR 却没跑、事后读 ESTAT 还是 0。
 *    板上实测 736 次等待里有 3~6 次(约 0.4%)正是这种情况，每次都让 CPU 读到
 *    加速器还没写完的输出。成因见 soc_top.v 的 CB_done 跨时钟域那段注释。
 *
 * 2) 丢失唤醒：加速器若在 CPU 执行到 `idle` 之前就完成，ISR 跑完会把完成电平撤掉，
 *    裸 `idle` 就会睡下去等一个已经过去的事件。实测 early_done=0 说明没触发过，
 *    但循环写法把它一并关掉，不必去论证它不会发生。 */
static inline void cpu_idle(void)
{
#ifdef __loongarch__
#if IDLE_WAKECNT
    /* 诊断：数清楚循环转了几圈，把两种竞态分开——
     *   0 圈：进循环前标志已置起，即加速器在 CPU 执行 idle **之前**就完成了
     *   1 圈：正常，idle 睡下、被完成中断叫醒
     *  >1 圈：idle **提前返回**了，这是原缺陷真正被触发的次数 */
    unsigned long nw = 0;
#endif
    while (!hwi1_flag) {
#if !NO_IDLE_INSN
        __asm__ __volatile__("idle 0" ::: "memory");
#endif
#if IDLE_WAKECNT
        nw++;
        /* idle 返回了但标志没置起 —— 这就是一次假唤醒。当场读 ESTAT/CRMD，
         * 让硬件自己交代是哪条中断线把 idle_lock 清掉的：
         *   IS[3]=1（HWI1）→ 加速器的完成电平确实来过，但中断没被取走
         *   IS 全 0        → 没有任何中断挂起，idle 是无故返回的
         *   CRMD.IE=0      → 唤醒发生在关中断窗口内 */
        if (!hwi1_flag && idle_samp_n < 8) {
            unsigned long es, cr;
            __asm__ __volatile__("csrrd %0, 0x5" : "=r"(es));
            __asm__ __volatile__("csrrd %0, 0x0" : "=r"(cr));
            idle_samp_estat[idle_samp_n] = es;
            idle_samp_crmd [idle_samp_n] = cr;
            idle_samp_n++;
        }
#endif
    }
#if IDLE_WAKECNT
    if (nw == 0)      idle_wake_zero++;
    else if (nw > 1)  idle_wake_extra += (nw - 1);
    idle_wait_total++;
#endif
    hwi1_flag = 0;
#if IDLE_WARMUP
    {
        volatile int w;
        for (w = 0; w < IDLE_WARMUP; w++) { }
    }
#endif
#endif
}

static inline void cb_write(unsigned long offset, unsigned long value)
{
    RegWrite(CB_BASE + offset, value);
}

static inline unsigned long cb_read(unsigned long offset)
{
    return RegRead(CB_BASE + offset);
}

void HWI1_IntrHandler(void){
    hwi1_ack();
    hwi1_flag = 1;   /* NO_IDLE_INSN 的自旋路径与 IDLE_PREDICATE 的谓词循环都看它 */
}

// Data Structures

typedef struct {
    int dim;        // transformer dimension
    int hidden_dim; // for FFN layers
    int n_layers;   // number of layers
    int n_heads;    // number of query heads
    int n_kv_heads; // number of key/value heads (can be < n_heads)
    int vocab_size; // vocabulary size
    int seq_len;    // max sequence length
} Config;

typedef struct {
    // token embedding table
    float* token_embedding_table;   // (vocab_size, dim)
    // weights for rmsnorms
    float* rms_att_weight;          // (layer, dim) rmsnorm weights
    float* rms_ffn_weight;          // (layer, dim)
    // weights for matmuls
    float* wq;                      // (layer, dim, n_heads * head_size)
    float* wk;                      // (layer, dim, n_kv_heads * head_size)
    float* wv;                      // (layer, dim, n_kv_heads * head_size)
    float* wo;                      // (layer, n_heads * head_size, dim)
    // weights for ffn
    float* w1;                      // (layer, hidden_dim, dim)
    float* w2;                      // (layer, dim, hidden_dim)
    float* w3;                      // (layer, hidden_dim, dim)
    // final rmsnorm
    float* rms_final_weight;        // (dim,)
    // classifier weights
    float* wcls;
} TransformerWeights;

typedef struct {
    // current wave of activations
    float *x;           // activation at current time stamp (dim,)
    float *xb;          // same, but inside a residual branch (dim,)
    float *xb2;         // an additional buffer for convenience (dim,)
    float *hb;          // buffer for hidden dimension in FFN (hidden_dim,)
    float *hb2;         // buffer for hidden dimension in FFN (hidden_dim,)
    float *q;           // query (dim,)
    float *k;           // key (kv_dim,)
    float *v;           // value (kv_dim,)
    float *att;         // buffer for scores/attention values (n_heads, seq_len)
    float *logits;      // output logits
    // kv cache
    float* key_cache;   // (layer, seq_len, kv_dim)
    float* value_cache; // (layer, seq_len, kv_dim)
} RunState;

typedef struct {
    Config config;
    TransformerWeights weights;
    RunState state;
    // pointer to the embedded model data
    float* data;
    size_t file_size;
} Transformer;

// ----------------------------------------------------------------------------
// Memory allocation and management

void malloc_run_state(RunState* s, Config* p) {
    int kv_dim = (p->dim * p->n_kv_heads) / p->n_heads;
    int head_size = p->dim / p->n_heads;
    int n_kv_heads = p->n_kv_heads;
    int max_tiles = (p->seq_len + head_size - 1) / head_size;
    int tile_size = n_kv_heads * head_size * head_size; // 每tile的float数
    s->x = calloc(p->dim, sizeof(float));
    s->xb = calloc(p->dim, sizeof(float));
    s->xb2 = calloc(p->dim, sizeof(float));
    s->hb = calloc(p->hidden_dim, sizeof(float));
    s->hb2 = calloc(p->hidden_dim, sizeof(float));
    s->q = calloc(p->dim, sizeof(float));
    s->k = calloc(kv_dim, sizeof(float));
    s->v = calloc(kv_dim, sizeof(float));
    s->att = calloc(p->n_heads * p->seq_len, sizeof(float));
    s->logits = calloc(p->vocab_size, sizeof(float));
    // KV cache使用tile-based布局，直接对应硬件DMA格式
    // 布局: [layer][tile][n_kv_heads × head_size × head_size]
    s->key_cache = calloc(p->n_layers * max_tiles * tile_size, sizeof(float));
    s->value_cache = calloc(p->n_layers * max_tiles * tile_size, sizeof(float));
    // ensure all mallocs were successful
    if (!s->x || !s->xb || !s->xb2 || !s->hb || !s->hb2 || !s->q
     || !s->k || !s->v || !s->att || !s->logits || !s->key_cache || !s->value_cache) {
        fprintf(stderr, "malloc failed in malloc_run_state!\n");
        exit(EXIT_FAILURE);
    }
}

void free_run_state(RunState* s) {
    free(s->x); free(s->xb); free(s->xb2); free(s->hb); free(s->hb2);
    free(s->q); free(s->k); free(s->v);
    free(s->att); free(s->logits);
    free(s->key_cache); free(s->value_cache);
}

void memory_map_weights(TransformerWeights *w, Config* p, float* ptr, int shared_weights) {
    int head_size = p->dim / p->n_heads;
    // make sure the multiplications below are done in 64bit to fit the parameter counts of 13B+ models
    unsigned long long n_layers = p->n_layers;
    w->token_embedding_table = ptr;
    ptr += p->vocab_size * p->dim;
    w->rms_att_weight = ptr;
    ptr += n_layers * p->dim;
    w->wq = ptr;
    ptr += n_layers * p->dim * (p->n_heads * head_size);
    w->wk = ptr;
    ptr += n_layers * p->dim * (p->n_kv_heads * head_size);
    w->wv = ptr;
    ptr += n_layers * p->dim * (p->n_kv_heads * head_size);
    w->wo = ptr;
    ptr += n_layers * (p->n_heads * head_size) * p->dim;
    w->rms_ffn_weight = ptr;
    ptr += n_layers * p->dim;
    w->w1 = ptr;
    ptr += n_layers * p->dim * p->hidden_dim;
    w->w2 = ptr;
    ptr += n_layers * p->hidden_dim * p->dim;
    w->w3 = ptr;
    ptr += n_layers * p->dim * p->hidden_dim;
    w->rms_final_weight = ptr;
    ptr += p->dim;
    ptr += p->seq_len * head_size / 2; // skip what used to be freq_cis_real (for RoPE)
    ptr += p->seq_len * head_size / 2; // skip what used to be freq_cis_imag (for RoPE)
    w->wcls = shared_weights ? w->token_embedding_table : ptr;
}

// CORRECTED: The order of operations in this function is now correct.
void build_transformer(Transformer *t) {
    // MODIFICATION: Instead of opening a file, point directly to the embedded data array.
    t->data = (float*)stories_bin;
    t->file_size = stories_bin_len;

    // Read the header metadata from the beginning of the data block
    float* data_ptr = t->data;

    // --- FIX START ---
    // 1. First, copy the config from the data blob into the transformer struct.
    memcpy(&t->config, data_ptr, sizeof(Config));

    // 2. Now that t->config is populated, we can use its values.
    // The negative vocab_size is a hacky way of signaling unshared weights.
    int shared_weights = t->config.vocab_size > 0 ? 1 : 0;
    t->config.vocab_size = abs(t->config.vocab_size);
    
    // 3. The weights start right after the config header.
    float* weights_ptr = data_ptr + (sizeof(Config) / sizeof(float));
    memory_map_weights(&t->weights, &t->config, weights_ptr, shared_weights);
    // --- FIX END ---

    // Allocate memory for the run state
    malloc_run_state(&t->state, &t->config);
}

void free_transformer(Transformer* t) {
    // MODIFICATION: Do NOT free t->data, as it points to a static array
    // in the executable's data segment, not heap-allocated memory.

    // Free the run state buffers
    free_run_state(&t->state);
}


// ----------------------------------------------------------------------------
// Neural net layers

void rmsnorm(float* o, float* x, float* weight, int size) {
    BP_MARK(bp_n0);
    // calculate sum of squares
    float ss = 0.0f;
    for (int j = 0; j < size; j++) {
        ss += x[j] * x[j];
    }
    ss /= size;
    ss += 1e-5f;
    ss = 1.0f / sqrtf(ss);
    // normalize and scale
    for (int j = 0; j < size; j++) {
        o[j] = weight[j] * (ss * x[j]);
    }
    BP_MARK(bp_n1);
    BP_ACC(BP_RMSNORM, bp_n0, bp_n1);
}

void softmax(float* x, int size) {
    if (size == 1) { x[0] = 1.0f; return; }
    // find max value (for numerical stability)
    float max_val = x[0];
    for (int i = 1; i < size; i++) {
        if (x[i] > max_val) {
            max_val = x[i];
        }
    }
    // exp and sum
    float sum = 0.0f;
    for (int i = 0; i < size; i++) {
        x[i] = expf(x[i] - max_val);
        sum += x[i];
    }
    // normalize
    for (int i = 0; i < size; i++) {
        x[i] /= sum;
    }
}

// ---- 构建模式：选择走硬件还是纯CPU（Makefile MODE=cpu 同时打开两个）----
#ifndef CPU_ONLY_MATMUL
#define CPU_ONLY_MATMUL 0   // 1: 矩阵乘走纯CPU（golden参考）
#endif
#ifndef CPU_ONLY_ATTN
#define CPU_ONLY_ATTN 0     // 1: 注意力走纯CPU（golden参考）
#endif

// ---- 性能分析（Makefile MM_REPORT=N / TOK_REPORT=N）----
#ifndef BENCH_MATMUL_REPORT_INTERVAL
#define BENCH_MATMUL_REPORT_INTERVAL 0  // >0: 每N次matmul打印累计均值
#endif
#ifndef BENCH_TOKEN_REPORT_INTERVAL
#define BENCH_TOKEN_REPORT_INTERVAL 0   // >0: 每N个token打印一次进度
#endif

// ---- 调试/对比开关：各自独立，默认全关，需要时单独打开 ----
#ifndef VERIFY_MATMUL
#define VERIFY_MATMUL 0     // CPU重算并逐元素比对硬件结果（Makefile VERIFY=1）
#endif
#ifndef DEBUG_NAN_CHECK
#define DEBUG_NAN_CHECK 0   // 每次matmul扫描n+2d个元素查NaN/Inf并在命中时停机。
                            // 开销随矩阵规模线性增长，会显著拖慢推理，默认关
                            // （Makefile NAN_CHECK=1）
#endif
#ifndef DEBUG_TRACE
#define DEBUG_TRACE 0       // 每次硬件调用完成打一行，仅bring-up定位卡死用
#endif
#ifndef HW_FPU
#define HW_FPU 0            // MODE=hw_fpu时由Makefile定义为1，仅用于区分[HWSW]打印
#endif

// 构建标识：开头和结尾两处[HWSW]打印共用同一个定义，避免各自判断导致不同步
// （曾因结尾改了、开头没改，同一次运行打出mode=hw和mode=hw_fpu两个矛盾标签，
//   使得无法确认板上烧的到底是哪个二进制）
#if CPU_ONLY_MATMUL
#define HWSW_MODE_NAME "cpu"
#elif HW_FPU
#define HWSW_MODE_NAME "hw_fpu"
#else
#define HWSW_MODE_NAME "hw"
#endif
#ifndef DUMP_TOKEN_SEQ
#define DUMP_TOKEN_SEQ 0    // 结束时打印token序列，用于两种模式的一致率对比
#endif
#ifndef DUMP_LOGITS
#define DUMP_LOGITS 0       // 结束时打印logit序列，用于PPL/KL精度对比
#endif
#ifndef DUMP_ACT
// 把非线性算子的真实输入值导出成二进制文件，供离线评估硬件近似方案（LUT/PWL）
// 的精度。评估必须用真实分布：合成的均匀采样会高估尾部、低估零附近的密度，
// 而 PWL 的误差恰恰集中在分段边界与曲率大的区间。
// 只在 host 构建下有意义（板上无文件系统），故与 __loongarch__ 互斥。
#define DUMP_ACT 0
#endif
#if DUMP_ACT && !defined(__loongarch__)
static FILE *g_act_silu = NULL;   // SiLU 输入 = w1(x)，每 token 每层 hidden_dim 个
static FILE *g_act_rope = NULL;   // RoPE 的 (pos, freq) 对，用于评估三角查表方案
#endif

#ifndef SILU_APPROX
// 用硬件位级模型替换 expf 算 SiLU，评估"把 SiLU 挪进硬件"对最终生成结果的影响。
// 算子级误差再小也只是中间量，唯一有意义的指标是生成的 token 是否改变——这个
// 开关就是为了拿这个答案，不是为了在 CPU 上跑得更快。
// 编译时需要 -I<repo>/tb/dpi 才能找到 fp_bitlevel.h。
#define SILU_APPROX 0
#endif
/* VERIFY_MATMUL 也要用位级 SiLU：w1 那一路的激活是**融合在硬件里**的，
 * 而 VERIFY 的 golden 只算裸 matmul，两边必然对不上——实测每层 7 个 matmul 里
 * 恰好错 1 个、形状永远是 d=hidden_dim n=dim、172 个输出错 163~171 个、
 * max_err 1~4。那是工具盲区不是加速器错，但看日志的人分辨不出来。
 * 用 silu_bits() 而不是 x/(1+expf(-x))：硬件走的是 exp2 分段 PWL，
 * 拿精确 SiLU 当 golden 会留下 PWL 的近似误差，照样报一堆假 FAIL。 */
#if SILU_APPROX || VERIFY_MATMUL
#include "fp_bitlevel.h"
// 直接调用 fp_bitlevel.h 里的 silu_bits()——那份是按 fsa_accumulator 的 7 条命令
// 逐条对应写的。这里不另写一份：运算顺序不同则截断点不同，两份实现一旦漂移，
// 这个开关验证的就不是将要实现的那个电路了。
static inline float silu_hw_bitlevel(float x)
{
    uint32_t xb; memcpy(&xb, &x, 4);
    uint32_t o = silu_bits(xb);
    float r; memcpy(&r, &o, 4); return r;
}
#endif

#if DEBUG_NAN_CHECK
static int matmul_call_count = 0;
#endif

/* READBACK / W2_READBACK 诊断用：独立的计数器与位模式取法，不搭 VERIFY_MATMUL 的车
 * （那个开关会让程序慢 12.7 倍，本身就把要测的现象掩盖掉）。
 * f2u_bits 两个开关都要用，守卫必须覆盖两者——只写 READBACK_CHECK 的话，
 * 单开 W2_READBACK 会在链接期报 undefined reference。 */
#if W2_PAD192
/* 把 w2 零填充到 192 列（6 个满列块），**数学结果逐位不变**：补的是 0，乘出来也是 0。
 * 这是检验"部分列块(172=5×32+12)是否为触发条件"的唯一干净做法——
 * 上一版直接把 n 改成 160/192/140 的实验**无效**：那样数学从 layer 0 起全错，
 * 后续数据变成垃圾值，而被测现象是时序敏感的，数据分布一变故障窗口就可能自然关闭，
 * "干净"分不清是形状变了还是数据变垃圾了。
 * 代价：5 层 × 64 行 × 192 列 × 4B ≈ 240KB 静态缓冲（.bss 落 dsram，3584K 够）。 */
#define W2P_ROWS 64
#define W2P_COLS 192
static float w2_pad[5 * W2P_ROWS * W2P_COLS];
static float hb_pad[W2P_COLS];
static int   w2_pad_ready = 0;

#endif

#if READBACK_CHECK || W2_READBACK || W1_READBACK
static inline uint32_t f2u_bits(float f)
{
    union { uint32_t u; float f; } c; c.f = f; return c.u;
}
#endif
#if READBACK_CHECK
static int rbk_call_count = 0;
static uint32_t rbk_pre_val = 0;
static int rbk_pre_valid = 0;
#endif

/* STAGE_HASH 诊断：把每 token / 每层 / 每阶段之后残差流 x 的哈希存起来，
 * **跑完再一次性打印**。绝不能边算边打——UART 115200 下一行 40 字符约 1.2 万拍，
 * 上百行会把运行时间翻几倍，又变成"仪器改变被测对象"（今天已栽三次：
 * memtest 测试区小于 cache、VERIFY 慢 12.7 倍、READBACK v1 的 2000 次空转）。
 *
 * 用法：同一份二进制多跑几次，比对两次的哈希序列，第一处不同就是数据最早分叉的
 * 位置（第几个 token、第几层、attention 还是 FFN）。这个判据**不依赖任何机制假设**。 */
#if STAGE_HASH
#define SH_MAX 512
static uint32_t sh_val[SH_MAX];
static int      sh_n = 0;
static inline uint32_t sh_hash(const float *v, int n)
{
    uint32_t h = 0x811c9dc5u;
    for (int i = 0; i < n; i++) {
        union { uint32_t u; float f; } c; c.f = v[i];
        h ^= c.u;
        h = (h << 5) | (h >> 27);
        h += 0x9e3779b9u;
    }
    return h;
}
static inline void sh_rec(const float *v, int n)
{
    if (sh_n < SH_MAX) sh_val[sh_n] = sh_hash(v, n);
    sh_n++;
}
static void sh_dump(void)
{
    printf("[SH] total=%d\n", sh_n);
    int m = sh_n < SH_MAX ? sh_n : SH_MAX;
    for (int i = 0; i < m; i++) printf("[SH] %d %08x\n", i, sh_val[i]);
}
#endif

static unsigned long long bench_matmul_calls = 0;
static unsigned long long bench_matmul_cycles_total = 0;
#if VERIFY_MATMUL
static int verify_total_calls = 0;
static int verify_mismatch_calls = 0;
static float verify_global_max_err = 0.0f;
static double verify_err_sum = 0.0;
static int verify_total_elements = 0;
static int verify_total_mismatches = 0;
static int verify_fail_by_n[8];
static int verify_fail_n_vals[8];
static int verify_n_bucket_cnt = 0;

static int verify_fsa_calls = 0;
static int verify_fsa_mismatch_calls = 0;
static float verify_fsa_global_max_err = 0.0f;

static int verify_find_bucket(int n) {
    for (int i = 0; i < verify_n_bucket_cnt; i++)
        if (verify_fail_n_vals[i] == n) return i;
    if (verify_n_bucket_cnt < 8) {
        verify_fail_n_vals[verify_n_bucket_cnt] = n;
        verify_fail_by_n[verify_n_bucket_cnt] = 0;
        return verify_n_bucket_cnt++;
    }
    return -1;
}
#endif

static inline void cache_flush(void *addr, size_t size)
{
#ifdef __loongarch__
    unsigned long line = 1 << cache_offset_width;
    unsigned long start = ((unsigned long)addr) & ~(line - 1);
    unsigned long end = ((unsigned long)addr + size + line - 1) & ~(line - 1);
    for (unsigned long p = start; p < end; p += line) {
        __asm__ __volatile__("cacop 0x11, %0, 0" :: "r"(p) : "memory");
    }
    __asm__ __volatile__("dbar 0" ::: "memory");
#else
    /* host 构建下没有需要维护一致性的 DMA buffer，空实现 */
    (void)addr; (void)size;
#endif
}

// uncached访问：将cached地址重映射到0xA0000000 uncached窗口
// 用于DMA buffer，避免cache flush开销
#if W2_PAD192
static void w2_pad_build(TransformerWeights *w, int dim_, int hidden_)
{
    for (int l2 = 0; l2 < 5; l2++) {
        const float *src = w->w2 + (size_t)l2 * dim_ * hidden_;
        float *dst = w2_pad + (size_t)l2 * W2P_ROWS * W2P_COLS;
        for (int r = 0; r < dim_; r++) {
            for (int c = 0; c < hidden_; c++) dst[r * W2P_COLS + c] = src[r * hidden_ + c];
            for (int c = hidden_; c < W2P_COLS; c++) dst[r * W2P_COLS + c] = 0.0f;
        }
    }
    cache_flush(w2_pad, sizeof(w2_pad));
    w2_pad_ready = 1;
}
#endif

static inline volatile float* uncached_f(void* ptr) {
#ifdef __loongarch__
    uintptr_t phys = (uintptr_t)ptr & 0x1fffffffu;
    return (volatile float*)(phys | 0xa0000000u);
#else
    /* host 构建没有 DMW uncached 窗口，也不存在与 DMA 的一致性问题，原样返回 */
    return (volatile float*)ptr;
#endif
}

static inline uint32_t to_phys(const void* ptr) {
    uintptr_t addr = (uintptr_t)ptr;
    if ((addr & 0xe0000000u) == 0xa0000000u)
        return (uint32_t)(addr & 0x1fffffffu);
    return (uint32_t)addr;
}

// matmul内部实现（skip_x_flush=1时跳过输入向量flush）
// SiLU硬件融合是否可用。
//   - CPU_ONLY_MATMUL 下根本不走硬件通路，激活只能留在软件里
//   - 允许 Makefile 用 SILU=0 强制关掉（-DHW_SILU_FUSED=0），得到一个"硬件GEMV +
//     软件激活"的对照组：与启用版跑同一模型比 token 序列和 FFN.act 耗时，
//     才能把硬件SiLU的收益和正确性单独量出来
#ifndef HW_SILU_FUSED
#if CPU_ONLY_MATMUL
#define HW_SILU_FUSED 0
#else
#define HW_SILU_FUSED 1
#endif
#endif

// 权重预取。默认开；PREFETCH=0（-DHW_PREFETCH=0）得到对照组，两版跑同一模型
// 比 GEMV.csr / GEMV.hw 净值，才能把预取的收益单独量出来。
// CPU_ONLY_MATMUL 下没有硬件通路，本开关无意义。
#ifndef HW_PREFETCH
#if CPU_ONLY_MATMUL
#define HW_PREFETCH 0
#else
#define HW_PREFETCH 1
#endif
#endif

// FSA侧K tile0预取，默认关（Makefile的FSA_PREFETCH=1打开）。硬件通路已验证、
// 实测40/40次全命中，但端到端净退化1.09%——它把K的搬运从CPU空闲的ATTN.hw段挪到了
// CPU忙碌的RoPE段，争用代价超过收益。详见Makefile里那段说明。
// 只做CSR前移、不发预取DMA的诊断模式（见 fsa_prefetch_k 内的说明）
#ifndef FSA_PF_CFGONLY
#define FSA_PF_CFGONLY 0
#endif
// 把预取调用挪到 attention 紧前面、不跨 RoPE 的诊断模式（见调用点说明）
#ifndef FSA_PF_LATE
#define FSA_PF_LATE 0
#endif
#ifndef HW_FSA_PREFETCH
#define HW_FSA_PREFETCH 0
#endif

// CSR配置段。预取路径和正常路径共用同一份，保证两边配的东西逐字节一致——
// 一旦不一致，硬件会因为"配置被改写"判定预取作废，白搬一趟。
static inline void matmul_cfg_addr(float* xout, float* x, float* w) {
    cb_write(REG_MI_BASE_ADDR, (unsigned long)w);
    cb_write(REG_VI_BASE_ADDR, (unsigned long)x);
    cb_write(REG_VO_BASE_ADDR, (unsigned long)xout);
}
static inline void matmul_cfg_dim(int n, int d, int silu_en) {
    cb_write(REG_ROWS_ADDR, d);
    cb_write(REG_COLS_ADDR, n);
    // 激活融合开关。电平型，必须每次都显式写——上一次开过而这次不写就会残留，
    // 让本该是纯GEMV的结果被多做一遍silu
    cb_write(REG_ACT_CTRL_ADDR, silu_en ? CSR_ACT_SILU_EN : 0);
}

// 发起权重预取后立即返回，不阻塞。硬件用刚配好的CSR把第一个权重行块搬进SRAM，
// CPU这边接着去算rmsnorm/SwiGLU，搬运就藏在那段计算里。
// 调用后到 matmul_pf_launch 之间，绝不能再碰 MI_BASE/ROWS/COLS——硬件据此判定
// 配置已变、预取作废（安全回退，不会算错，只是白搬一趟）。
static void matmul_prefetch(float* xout, float* x, float* w, int n, int d, int silu_en) {
    matmul_cfg_addr(xout, x, w);
    matmul_cfg_dim(n, d, silu_en);
    cb_write(REG_PF_CTRL_ADDR, CSR_PF_START_BIT | CSR_PF_TGT_GEMV);
}

// silu_en=1 时让硬件在结果写回DDR之前就地过一遍 silu()，省掉CPU侧那趟
// expf+除法（实测占总时间18.67%）。硬件复用FSA的4个累加器通道跑7步微程序，
// 无新增算术单元；CPU这边只是多写一个CSR。
// cfg_done=1 表示CSR已由matmul_prefetch配好，这里必须跳过配置段——重复写会把
// 硬件那边的pf_valid清掉，预取就白做了。
static void matmul_inner(float* xout, float* x, float* w, int n, int d,
                         int skip_x_flush, int silu_en, int cfg_done) {
    unsigned long start_cycles = get_cpu_clock_count();
#if CPU_ONLY_MATMUL
    for (int i = 0; i < d; i++) {
        float sum = 0.0f;
        for (int j = 0; j < n; j++) {
            sum += w[i * n + j] * x[j];
        }
        xout[i] = sum;
    }
#else
    // 硬件控制器负责内部的分块循环和地址计算，CPU只配寄存器+等中断。
    // 下面按 CSR配置 / cache flush / 等硬件 三段分别计时，用于回答
    // "时间到底花在CPU侧胶水还是硬件本身"（BENCH=0时所有BP_*展开为空）
    BP_MARK(bp_t0);

    // 设置整个权重矩阵 w、输入向量 x 和输出向量 xout 的起始基地址。
    if (!cfg_done)
        matmul_cfg_addr(xout, x, w);
    BP_MARK(bp_t1);

    //Software Cache flush
    if (!skip_x_flush)
        cache_flush(x, (size_t)n * sizeof(float));
    // 权重w是只读静态数据，build后已一次性flush，不再重复
    cache_flush(xout, (size_t)d * sizeof(float));
    BP_MARK(bp_t2);

    // 设置整个任务的总维度 (例如，对于64x64矩阵，d=64, n=64)。
    if (!cfg_done)
        matmul_cfg_dim(n, d, silu_en);

    // --- 2. 启动硬件引擎 ---
    // 诊断开关（Makefile PRE_START_DELAY=N）：启动加速器**之前**空转 N 次。
    //
    // 它和 IDLE_WARMUP 是一对对照实验。IDLE_WARMUP 把延迟放在唤醒之后，同时
    // 拉长了两件事：①唤醒到浮点运算的间隔 ②加速器两次操作之间的间隔——分不清
    // 是哪个起作用。放在这里则只拉长②，浮点运算仍然紧挨着唤醒：
    //   仍然出错 → 关键是①，与加速器占空比无关
    //   变正确   → 关键是②，与 FPU 无关，指向加速器的功耗/占空比
    // 数字上四个已知点（每 token 46 次加速器调用，算每次操作间的 CPU 空隙）
    // 一致指向②：hw 67k 拍✅ / warm1000 17k 拍✅ / warm100 8k 拍❌ / 原版 7k 拍❌。
#if PRE_START_DELAY
    { volatile int w; for (w = 0; w < PRE_START_DELAY; w++) { } }
#endif
#if READBACK_CHECK
    /* 启动前记下输出缓冲首字，供唤醒后判别"读到的是不是加速器写之前的旧内容" */
    { volatile float *xo_pre = uncached_f(xout);
      rbk_pre_val = f2u_bits(xo_pre[0]); rbk_pre_valid = 1; }
#endif
    // 发送一个启动命令。硬件控制器收到后，将开始其内部分块循环。
    hw_arm();
    cb_write(REG_CTRL_ADDR, CSR_CTRL_START_BIT);
    BP_MARK(bp_t3);

    // --- 3. 等待硬件完成整个大任务 (等待一次中断) ---
    // CPU进入休眠，等待硬件处理完所有分块后发出的唯一一次完成中断。
    // bp_t3→bp_t4 即纯硬件时间（DMA搬权重 + PE阵列计算）
    cpu_idle();

#if READBACK_CHECK
    // 诊断（Makefile READBACK=1）：判定"唤醒后立刻读"拿到的是不是旧值。
    //
    // **必须近乎零开销**：第一版在两次读之间放了 2000 次空转，结果 cycles_per_token
    // 从 486K 涨到 995K，探针本身就成了 IDLE_WARMUP 把 bug 修掉了（零条报告、
    // token 全对）。今天第三次撞上"仪器改变被测对象"。
    //
    // 现在只做三次非缓存读，共约 60 拍：
    //   pre   —— 启动加速器**之前**该地址的内容（由下方 START 前那段捕获）
    //   early —— 唤醒后立刻读
    //   late  —— 紧接着再读一次（不加任何延迟）
    // 判别：
    //   early == pre   → 读到了加速器写之前的旧内容（写没落盘 / 读得太早）
    //   early != late  → 读通路本身不稳定
    //   两者都不成立   → 这条路径清白，错在别处
    {
        volatile float *xo_uc = uncached_f(xout);
        uint32_t early = f2u_bits(xo_uc[0]);
        uint32_t late  = f2u_bits(xo_uc[0]);
        if (early == rbk_pre_val && rbk_pre_valid) {
            printf("[RBK] call#%d d=%d EARLY==PRE early=%08x pre=%08x late=%08x\n",
                   rbk_call_count, d, early, rbk_pre_val, late);
        } else if (early != late) {
            printf("[RBK] call#%d d=%d UNSTABLE early=%08x late=%08x pre=%08x\n",
                   rbk_call_count, d, early, late, rbk_pre_val);
        }
        rbk_call_count++;
    }
#endif

    // --- 4. 应答中断 ---
    // 唤醒后，清除硬件的中断状态。这里只做应答动作，不能调 ISR 本体——
    // ISR 会把 hwi1_flag 置起，NO_IDLE_INSN 的自旋路径下会让**下一次**等待直接穿过去。
    hwi1_ack();
    BP_MARK(bp_t4);

    BP_ACC(BP_GEMV_CSR,   bp_t0, bp_t1);
    BP_ACC(BP_GEMV_FLUSH, bp_t1, bp_t2);
    BP_ACC(BP_GEMV_CSR,   bp_t2, bp_t3);  // 维度+启动也算CSR配置开销
    BP_ACC(BP_GEMV_HW,    bp_t3, bp_t4);
    BP_ADD_GEMV_SCALE(n, d);

#if DEBUG_TRACE
    printf("[TRACE] gemv done n=%d d=%d\n", n, d);
#endif

#if DEBUG_NAN_CHECK
    // NaN检测（hex打印，避免触发strtod_l死循环）。
    // 会遍历 n+2d 个元素，开销随矩阵规模线性增长，故默认关闭；
    // 命中异常时直接 while(1) 停机，便于在板上定位是哪一次调用算坏的。
    BP_MARK(bp_t5);
    {
        static unsigned int prev_w, prev_x, prev_xout;
        static int prev_d, prev_n;
        matmul_call_count++;
        // 先检查输入向量是否有NaN/Inf
        unsigned int *xv = (unsigned int*)x;
        int x_bad = 0;
        for (int j = 0; j < n; j++) {
            if ((xv[j] & 0x7F800000) == 0x7F800000) { x_bad++; }
        }
        if (x_bad > 0) {
            printf("[X_BAD] call#%d d=%d n=%d x has %d NaN/Inf (of %d)\n", matmul_call_count, d, n, x_bad, n);
            printf("[X_BAD] w=%08x x=%08x xout=%08x\n", (unsigned)w, (unsigned)x, (unsigned)xout);
            printf("[PREV] call#%d d=%d n=%d w=%08x x=%08x xout=%08x\n",
                   matmul_call_count-1, prev_d, prev_n, prev_w, prev_x, prev_xout);
            printf("[X_ALL]");
            for (int j = 0; j < n; j++) {
                if ((xv[j] & 0x7F800000) == 0x7F800000)
                    printf(" [%d]=%08x!", j, xv[j]);
            }
            printf("\n");
            while(1);
        }
        // 检查输出是否有Inf或NaN（输入正常但输出异常 = 这次matmul溢出）
        unsigned int *out_u = (unsigned int*)xout;
        for (int i = 0; i < d; i++) {
            unsigned int v = out_u[i];
            if ((v & 0x7F800000) == 0x7F800000) {  // exp全1 = Inf或NaN
                printf("[BAD_OUT] call#%d d=%d n=%d row=%d val=%08x (input clean!)\n", matmul_call_count, d, n, i, v);
                printf("[BAD_OUT] w=%08x x=%08x xout=%08x\n", (unsigned)w, (unsigned)x, (unsigned)xout);
                printf("[VEC]");
                for (int j = 0; j < (n < 16 ? n : 16); j++) printf(" %08x", xv[j]);
                printf("\n");
                unsigned int *wrow = (unsigned int*)&w[i*n];
                printf("[W%d]", i);
                for (int j = 0; j < (n < 16 ? n : 16); j++) printf(" %08x", wrow[j]);
                printf("\n");
                // 打印所有异常位置
                printf("[O_BAD]");
                for (int k = 0; k < d; k++) {
                    if ((out_u[k] & 0x7F800000) == 0x7F800000)
                        printf(" [%d]=%08x!", k, out_u[k]);
                }
                printf("\n");
                while(1);
            }
        }
        // 跟踪输出最大绝对值（检测是否逐渐增长）
        {
            unsigned int max_abs = 0;
            int max_idx = 0;
            for (int i = 0; i < d; i++) {
                unsigned int abs_v = out_u[i] & 0x7FFFFFFF;
                if (abs_v > max_abs) { max_abs = abs_v; max_idx = i; }
            }
            // exp >= 0x4F (即|value| >= 2^31 ≈ 2.1e9) 时报警
            if ((max_abs & 0x7F800000) >= 0x4F000000) {
                printf("[LARGE] call#%d d=%d n=%d row=%d val=%08x\n", matmul_call_count, d, n, max_idx, out_u[max_idx]);
            }
        }
        prev_w = (unsigned int)w; prev_x = (unsigned int)x; prev_xout = (unsigned int)xout;
        prev_d = d; prev_n = n;
    }
    BP_MARK(bp_t6);
    BP_ACC(BP_GEMV_POST, bp_t5, bp_t6);
#endif /* DEBUG_NAN_CHECK */

#if VERIFY_MATMUL
    // CPU对比验证
    {
        verify_total_calls++;
        int mismatch = 0;
        float max_err = 0.0f;
        int max_err_idx = 0;
        double err_sum_local = 0.0;
        for (int i = 0; i < d; i++) {
            float cpu_val = 0.0f;
            for (int j = 0; j < n; j++) {
                cpu_val += w[i * n + j] * x[j];
            }
            // silu_en=1 时硬件在写回前就地过了一遍激活（只有 FFN 的 w1 这一路），
            // golden 必须跟着做，否则这一路 100% 报 FAIL 而与加速器无关。
            if (silu_en) cpu_val = silu_hw_bitlevel(cpu_val);
            float diff = fabsf(cpu_val - xout[i]);
            err_sum_local += diff;
            if (diff > max_err) {
                max_err = diff;
                max_err_idx = i;
            }
            if (diff > 1e-2f) {
                mismatch++;
            }
        }
        verify_total_elements += d;
        verify_err_sum += err_sum_local;
        if (max_err > verify_global_max_err)
            verify_global_max_err = max_err;
        if (mismatch > 0) {
            verify_mismatch_calls++;
            verify_total_mismatches += mismatch;
            int b = verify_find_bucket(n);
            if (b >= 0) verify_fail_by_n[b]++;
            printf("[VERIFY] FAIL call#%d d=%d n=%d mismatches=%d max_err=%.6f@idx=%d\n",
                   verify_total_calls, d, n, mismatch, max_err, max_err_idx);
        } else if ((verify_total_calls % 64) == 0) {
            printf("[VERIFY] OK call#%d max_err=%.6f\n", verify_total_calls, max_err);
        }
    }
#endif

#endif

    {
        unsigned long end_cycles = get_cpu_clock_count();
        unsigned long delta = end_cycles - start_cycles;
        bench_matmul_calls++;
        bench_matmul_cycles_total += (unsigned long long)delta;
#if BENCH_MATMUL_REPORT_INTERVAL > 0
        if ((bench_matmul_calls % BENCH_MATMUL_REPORT_INTERVAL) == 0) {
            unsigned long long avg_cycles = bench_matmul_cycles_total / bench_matmul_calls;
            printf("\n[BENCH] matmul_progress calls=%llu total_cycles=%llu avg_cycles=%llu\n",
                   bench_matmul_calls, bench_matmul_cycles_total, avg_cycles);
        }
#endif
    }
}

// matmul标准接口（flush输入向量）
void matmul(float* xout, float* x, float* w, int n, int d) {
    matmul_inner(xout, x, w, n, d, 0, 0, 0);
}

// matmul跳过输入flush（连续调用同一输入时使用）
void matmul_nf(float* xout, float* x, float* w, int n, int d) {
    matmul_inner(xout, x, w, n, d, 1, 0, 0);
}

// matmul + 硬件SiLU融合：结果写回DDR前已经是 silu(w·x)，CPU不必再算expf。
// 只用在FFN的w1那一路——w3(x)不过激活，attention/logits路径同理。
void matmul_silu(float* xout, float* x, float* w, int n, int d) {
    matmul_inner(xout, x, w, n, d, 0, 1, 0);
}

// 预取过的matmul：CSR已由matmul_prefetch配好，这里只flush+启动+等中断。
// flush必须留在这里而不能提前——x的内容是刚才那段CPU计算的产物，预取时还没算出来。
static void matmul_pf_launch(float* xout, float* x, float* w, int n, int d, int silu_en) {
    matmul_inner(xout, x, w, n, d, 0, silu_en, 1);
}

// 预取的成对宏。PREFETCH=0 时 BEGIN 退化为空、END 退化为普通matmul，
// 调用点写法不变，编译期就切干净，运行时零判断。
#if HW_PREFETCH
#define MATMUL_PF_BEGIN(xout, x, w, n, d, silu) \
    matmul_prefetch((xout), (x), (w), (n), (d), (silu))
#define MATMUL_PF_END(xout, x, w, n, d, silu) \
    matmul_pf_launch((xout), (x), (w), (n), (d), (silu))
#else
#define MATMUL_PF_BEGIN(xout, x, w, n, d, silu) ((void)0)
#define MATMUL_PF_END(xout, x, w, n, d, silu) \
    matmul_inner((xout), (x), (w), (n), (d), 0, (silu), 0)
#endif


// ============================================================================
// FSA硬件加速Attention
// ============================================================================

// FSA工作缓冲区（静态分配，避免每次malloc）
static float fsa_q_buf[4 * 8] __attribute__((aligned(16)));
static float fsa_o_buf[4 * 8] __attribute__((aligned(16)));

// 将K/V向量scatter到tile-based cache布局（通过uncached写入，无需flush）
// cache布局: [layer][tile][n_kv_heads × head_size × head_size]
static void store_kv_to_cache(float* cache, int loff, int pos,
                               float* kv_vec, int kv_dim, int head_size) {
    BP_MARK(bp_kv0);
    int tile_idx = pos / head_size;
    int row_in_tile = pos % head_size;
    int n_kv_heads = kv_dim / head_size;

    for (int g = 0; g < n_kv_heads; g++) {
        float* dst = cache + loff + tile_idx * n_kv_heads * head_size * head_size
                   + g * head_size * head_size + row_in_tile * head_size;
        volatile float* dst_uc = uncached_f(dst);
        float* src = kv_vec + g * head_size;
        for (int i = 0; i < head_size; i++)
            dst_uc[i] = src[i];
    }
    BP_MARK(bp_kv1);
    BP_ACC(BP_KVSTORE, bp_kv0, bp_kv1);
}

// FSA硬件在4×8分组下每趟处理4个Q组（NUM_ACTIVE=4）。硬件几何常量，非模型参数。
#define FSA_NUM_ACTIVE 4

// FSA模式硬件加速attention（GQA fanout版）
//
// 硬件支持"一份KV读一次、写Input SRAM时广播到ratio个Q组"（CB_top_v2.sv的
// k/v_fanout_bank_we）。软件按KV头分趟，让每个唯一KV头只从DDR读一次：
//   ratio=kv_mul；kv_per_pass=NUM_ACTIVE/ratio；num_passes=n_heads/NUM_ACTIVE
// stories260K(n_heads=8,n_kv_heads=4,kv_mul=2)：ratio=2,kv_per_pass=2,num_passes=2
//   pass0: Q0..3→读KV0,KV1，fanout KV0→组{0,1}、KV1→组{2,3}
//   pass1: Q4..7→读KV2,KV3
//   KV总读量4次（旧版每趟读全部4头共8次）→ 省50% DDR读带宽。
// 组g的Q头=pass*NUM_ACTIVE+g，KV头=(pass*NUM_ACTIVE+g)/kv_mul，与硬件fanout映射吻合。
// 保留本app的uncached访存风格（to_phys/uncached_f，不用cache_flush）。
// cfg_done=1 表示 pass 0 的 CSR 已由 fsa_prefetch_k() 配好，本函数必须跳过 pass 0
// 的配置段——重复写 K_BASE/HEAD_DIM/KV_STRIDE/NUM_HEADS 任何一个都会让硬件判定
// "配置已变"从而作废预取（安全回退，不会算错，只是白搬一趟）。pass 1 照常全配。
static void attention_fsa_fanout(RunState* s, Config* p, int pos, int loff, int cfg_done) {
    int head_size = p->dim / p->n_heads;
    int seq_len = pos + 1;
    int n_kv_heads = p->n_kv_heads;
    int kv_mul = p->n_heads / p->n_kv_heads;

    int ratio        = kv_mul;
    int kv_per_pass   = FSA_NUM_ACTIVE / ratio;
    int num_passes    = p->n_heads / FSA_NUM_ACTIVE;
    int kv_head_bytes = head_size * head_size * (int)sizeof(float); // 单KV头一个tile字节数
    int kv_stride     = n_kv_heads * kv_head_bytes;                 // tile间步长=物理全部KV头

    float* k_base = s->key_cache + loff;
    float* v_base = s->value_cache + loff;
    unsigned int scale_bits = 0x3F0293EE;

    for (int pass = 0; pass < num_passes; pass++) {
        int kv_start = pass * kv_per_pass;  // 本趟起始KV头
        unsigned long k_pass = (unsigned long)k_base + (unsigned long)kv_start * kv_head_bytes;
        unsigned long v_pass = (unsigned long)v_base + (unsigned long)kv_start * kv_head_bytes;

        // 准备Q：本趟NUM_ACTIVE个连续Q头（pass*NUM_ACTIVE+g），uncached写入避免flush
        volatile float* q_uc = uncached_f(fsa_q_buf);
        for (int g = 0; g < FSA_NUM_ACTIVE; g++) {
            int q_head_idx = pass * FSA_NUM_ACTIVE + g;
            float* src = s->q + q_head_idx * head_size;
            for (int i = 0; i < head_size; i++)
                q_uc[g * head_size + i] = src[i];
        }

        BP_MARK(bp_a0);
        if (!(cfg_done && pass == 0)) {
            cb_write(REG_Q_BASE_ADDR, to_phys(fsa_q_buf));
            cb_write(REG_K_BASE_ADDR, k_pass);
            cb_write(REG_V_BASE_ADDR, v_pass);
            cb_write(REG_O_BASE_ADDR, to_phys(fsa_o_buf));
            cb_write(REG_HEAD_DIM_ADDR, head_size);
            cb_write(REG_SEQ_LEN_ADDR, seq_len);
            cb_write(REG_KV_STRIDE_ADDR, kv_stride);
            cb_write(REG_NUM_HEADS_ADDR, kv_per_pass);  // 本趟唯一KV头数，硬件据此fanout
            cb_write(REG_ATTN_SCALE_ADDR, scale_bits);
        }

        hw_arm();
        cb_write(REG_CTRL_ADDR, CSR_CTRL_START_BIT | CSR_CTRL_MODE_FSA);
        BP_MARK(bp_a1);
        cpu_idle();
        hwi1_ack();   /* 同上：只应答，不走 ISR 本体 */
        BP_MARK(bp_a2);
        BP_ACC(BP_ATTN_CSR, bp_a0, bp_a1);
        BP_ACC(BP_ATTN_HW,  bp_a1, bp_a2);

        // uncached读回DMA结果（组g→Q头pass*NUM_ACTIVE+g）
        volatile float* o_uc = uncached_f(fsa_o_buf);
        for (int g = 0; g < FSA_NUM_ACTIVE; g++) {
            int q_head_idx = pass * FSA_NUM_ACTIVE + g;
            float* dst = s->xb + q_head_idx * head_size;
            for (int i = 0; i < head_size; i++)
                dst[i] = o_uc[g * head_size + i];
        }
    }
}

// 旧路径：每趟读全部n_kv_heads头（不省带宽但对任意config正确）。硬件不再兜底，
// REG_NUM_HEADS必配——一趟NUM_ACTIVE个独立组、ratio=1，故显式写n_kv_heads
// （legacy触发场景n_kv_heads==NUM_ACTIVE）。fanout分解条件不满足时退回此路径。
static void attention_fsa_legacy(RunState* s, Config* p, int pos, int loff) {
    int head_size = p->dim / p->n_heads;
    int seq_len = pos + 1;
    int n_kv_heads = p->n_kv_heads;
    int kv_mul = p->n_heads / p->n_kv_heads;
    int kv_stride = n_kv_heads * head_size * head_size * (int)sizeof(float);

    float* k_base = s->key_cache + loff;
    float* v_base = s->value_cache + loff;
    unsigned int scale_bits = 0x3F0293EE;

    for (int pass = 0; pass < kv_mul; pass++) {
        volatile float* q_uc = uncached_f(fsa_q_buf);
        for (int g = 0; g < n_kv_heads; g++) {
            int q_head_idx = pass + g * kv_mul;
            float* src = s->q + q_head_idx * head_size;
            for (int i = 0; i < head_size; i++)
                q_uc[g * head_size + i] = src[i];
        }

        BP_MARK(bp_a0);
        cb_write(REG_Q_BASE_ADDR, to_phys(fsa_q_buf));
        cb_write(REG_K_BASE_ADDR, (unsigned long)k_base);
        cb_write(REG_V_BASE_ADDR, (unsigned long)v_base);
        cb_write(REG_O_BASE_ADDR, to_phys(fsa_o_buf));
        cb_write(REG_HEAD_DIM_ADDR, head_size);
        cb_write(REG_SEQ_LEN_ADDR, seq_len);
        cb_write(REG_KV_STRIDE_ADDR, kv_stride);
        cb_write(REG_NUM_HEADS_ADDR, n_kv_heads);   // 必配：本趟n_kv_heads个独立KV头
        cb_write(REG_ATTN_SCALE_ADDR, scale_bits);

        hw_arm();
        cb_write(REG_CTRL_ADDR, CSR_CTRL_START_BIT | CSR_CTRL_MODE_FSA);
        BP_MARK(bp_a1);
        cpu_idle();
        hwi1_ack();   /* 同上：只应答，不走 ISR 本体 */
        BP_MARK(bp_a2);
        BP_ACC(BP_ATTN_CSR, bp_a0, bp_a1);
        BP_ACC(BP_ATTN_HW,  bp_a1, bp_a2);

        volatile float* o_uc = uncached_f(fsa_o_buf);
        for (int g = 0; g < n_kv_heads; g++) {
            int q_head_idx = pass + g * kv_mul;
            float* dst = s->xb + q_head_idx * head_size;
            for (int i = 0; i < head_size; i++)
                dst[i] = o_uc[g * head_size + i];
        }
    }
}

// fanout快路径适用条件（全满足才走省带宽路径，否则退legacy）：
// kv_mul整除NUM_ACTIVE(kv_per_pass正整数,排除kv_mul>4) & n_heads整除NUM_ACTIVE & n_heads>=NUM_ACTIVE
static int fsa_fanout_ok(Config* p) {
    int kv_mul = p->n_heads / p->n_kv_heads;
    if (kv_mul <= 0 || (FSA_NUM_ACTIVE % kv_mul) != 0) return 0;
    if (p->n_heads < FSA_NUM_ACTIVE) return 0;
    if ((p->n_heads % FSA_NUM_ACTIVE) != 0) return 0;
    return 1;
}

// 把 pass 0 的 FSA CSR 全配好并触发 K tile 0 的预取，立即返回。搬运藏进随后的 RoPE
// （实测 RoPE 占总时间 36%，窗口绰绰有余），CPU 算完 RoPE 时 K 已经在片上。
//
// 为什么在 RoPE 之前就能确定地址：k_base = key_cache + loff，而 loff 只依赖层号与
// max_tiles，RoPE 之前就算好了；历史 KV cache 也早已躺在内存里——store_kv_to_cache
// 写的只是当前 pos 那一格，且发生在 RoPE 之后。
//
// 正确性边界 pos >= head_size：K tile 0 覆盖序列位置 0 ~ head_size-1，pos 落在这个
// 区间时 tile 0 **包含当前 pos**，而那一格要等 RoPE 之后才写。256 个 token 里只有
// 前 head_size 个不预取。
//
// 只对 pass 0 有效：pass 1 的 K 地址不同，且两趟之间没有 CPU 段可藏。
// head_dim>32 时硬件不置 pf_valid（dual_chunk 要两笔 DMA，第一版不支持），
// 软件这边照发即可，硬件会安全地退回正常搬运。
// noinline 是必需的，不是风格选择：本函数带进 head_size/ratio/kv_per_pass/
// kv_head_bytes/kv_stride 等一批长生命期整数量，-O3 内联进 forward() 后会把那个
// 巨型函数的寄存器压力顶上去。寄存器分配是全函数范围的一次性决策，编译器按静态
// 代价模型挑谁溢出，并不知道 RoPE 那个循环整轮推理要跑 2560 次——一旦把跨越该
// 循环存活的值溢出到栈，每次迭代都要多付一次访存。
// 实测（16 token）：内联版让 forward() 从 968 条指令涨到 1044、整数 ld.w 从 249
// 涨到 275（浮点存取一条没变），端到端 ROPE +26,163 / RMSNORM +33,994，净退化
// 1.09%——而这两段是纯 CPU 浮点计算，跟 attention 毫无关系，纯粹是同一函数体内
// 共用寄存器分配导致的耦合。
__attribute__((noinline))
static int fsa_prefetch_k(RunState* s, Config* p, int pos, int loff) {
#if HW_FSA_PREFETCH && HW_PREFETCH && !CPU_ONLY_ATTN
    int head_size = p->dim / p->n_heads;
    if (pos < head_size) return 0;          // tile 0 含当前 pos，还没写进 cache
    if (!fsa_fanout_ok(p)) return 0;        // legacy 路径的 CSR 用法不同，不预取

    int ratio         = p->n_heads / p->n_kv_heads;
    int kv_per_pass   = FSA_NUM_ACTIVE / ratio;
    int kv_head_bytes = head_size * head_size * (int)sizeof(float);
    int kv_stride     = p->n_kv_heads * kv_head_bytes;

    // 把这9个CSR写也计进 ATTN.csr：它们本来就是 attention 的配置，只是被提前了。
    // 计进同一个槽位，两版的 ATTN.csr 才直接可比——否则预取版的写会掉进 other 那个
    // 残差桶里，只能靠减法推断，推断出来的"75拍/次 vs 8.3拍/次"必须变成实测才算数。
    BP_MARK(bp_pf0);
    // pass 0 的 kv_start=0，所以 k_pass 就是 k_base
    cb_write(REG_Q_BASE_ADDR, to_phys(fsa_q_buf));
    cb_write(REG_K_BASE_ADDR, (unsigned long)(s->key_cache + loff));
    cb_write(REG_V_BASE_ADDR, (unsigned long)(s->value_cache + loff));
    cb_write(REG_O_BASE_ADDR, to_phys(fsa_o_buf));
    cb_write(REG_HEAD_DIM_ADDR, head_size);
    cb_write(REG_SEQ_LEN_ADDR, pos + 1);
    cb_write(REG_KV_STRIDE_ADDR, kv_stride);
    cb_write(REG_NUM_HEADS_ADDR, kv_per_pass);
    cb_write(REG_ATTN_SCALE_ADDR, 0x3F0293EE);
#if !FSA_PF_CFGONLY
    // FSA_PF_CFGONLY=1 时只做CSR前移、不发预取DMA：用来把"配置前移"与"DMA挪到
    // CPU忙碌期"两个因素拆开——ATTN.hw 那 +10,567 拍到底来自哪一个。
    // 注意此时 pf_valid 不会置起，attention 走正常搬运路径，结果仍然正确。
    cb_write(REG_PF_CTRL_ADDR, CSR_PF_START_BIT | CSR_PF_TGT_FSA_K);
#endif
    BP_MARK(bp_pf1);
    BP_ACC(BP_ATTN_CSR, bp_pf0, bp_pf1);
    return 1;
#else
    (void)s; (void)p; (void)pos; (void)loff;
    return 0;
#endif
}

static void attention_fsa(RunState* s, Config* p, int pos, int loff, int cfg_done) {
    if (fsa_fanout_ok(p))
        attention_fsa_fanout(s, p, pos, loff, cfg_done);   // 省带宽快路径
    else
        attention_fsa_legacy(s, p, pos, loff);             // 通用回退
}


float* forward(Transformer* transformer, int token, int pos) {

    // a few convenience variables
    Config* p = &transformer->config;
    TransformerWeights* w = &transformer->weights;
    RunState* s = &transformer->state;
    float *x = s->x;
    int dim = p->dim;
    int kv_dim = (p->dim * p->n_kv_heads) / p->n_heads;
    int kv_mul = p->n_heads / p->n_kv_heads; // integer multiplier of the kv heads to the query heads
    int hidden_dim =  p->hidden_dim;
    int head_size = dim / p->n_heads;

    // copy the token embedding into x
    float* content_row = w->token_embedding_table + token * dim;
    memcpy(x, content_row, dim * sizeof(float));

    // ---- RoPE 的 (fcr,fci) 每 token 只算 head_size/2 组 ----
    // 原来这三个超越函数写在 RoPE 的 i 循环里，每层每两个元素算一次：
    // 256 token 实测 n=40960，即**每 token 算了 160 次**（5 层 × 32 次迭代）。
    // 但 freq 只取决于 head_dim = i % head_size（head_size=8 → 只有 {0,2,4,6} 四种），
    // val = pos*freq 只取决于 pos 与 head_dim —— **都不依赖层号 l，也不依赖 i 的具体值**。
    // 所以每 token 实际只有 head_size/2 = 4 个不同的 (fcr,fci)。
    // 提到层循环外面，160 次 → 4 次，而且是**同一个函数、同一个参数**，结果逐位相同，
    // 不是查表近似。BENCH 里 ROPE.trig 占 41.10%，这一刀直接冲它去。
    // 上限保护：head_size 由模型头决定，这里按最大 64 开静态数组（当前模型 head_size=8）。
    // 诊断开关（Makefile NO_ROPE_HOIST=1）：整段跳过，下面的 i 循环退回逐次算超越函数，
    // 即优化前的原始写法。用来在**当前这条干净基线上**重新标定这一刀的净收益——
    // 原先那组数（486,256 → 304,432）是在 idle 假唤醒还没修的时候测的，抖动 >13%，
    // 不足以支撑一个百分比结论。
#if !NO_ROPE_HOIST
    /* 表长决定能支持的最大 head_size：下面 i 循环按 rope_fcr[head_dim>>1] 取值，
     * head_dim = i % head_size < head_size，故需要 head_size/2 项。
     * 32 项 → 支持 head_size ≤ 64。head_size = dim/n_heads 是**运行期**值，
     * 由模型头决定（当前模型 dim=64 / n_heads=8 → head_size=8，用 4 项）。 */
#define ROPE_MAX_NFREQ 32
    float rope_fcr[ROPE_MAX_NFREQ], rope_fci[ROPE_MAX_NFREQ];
    {
        int nfreq = head_size / 2;
        /* 这里原来写的是"截断到 32，发生了就退回逐次计算的老路"——**那句话是假的**，
         * 根本没有那条老路：截断只限制填了几项，下面的 i 循环仍然无条件按下标取，
         * head_size>64 时会读到表外，而且是**静默错值**。
         * 所以改成直接停机报错：算错比停机更糟。要支持更大的 head_size
         * （llama2-7B 就是 128），把 ROPE_MAX_NFREQ 调大即可，别再截断。 */
        if (nfreq > ROPE_MAX_NFREQ) {
            printf("[FATAL] head_size=%d needs %d RoPE entries > ROPE_MAX_NFREQ=%d\n",
                   head_size, nfreq, ROPE_MAX_NFREQ);
            while (1) { }
        }
        for (int k = 0; k < nfreq; k++) {
            int   head_dim = k * 2;
            float freq = 1.0f / powf(10000.0f, head_dim / (float)head_size);
            float val  = pos * freq;
            rope_fcr[k] = cosf(val);
            rope_fci[k] = sinf(val);
        }
    }
#endif

    // forward all the layers
    for(unsigned long long l = 0; l < p->n_layers; l++) {

        // 预取wq的第一个权重行块，搬运藏进下面这段rmsnorm。
        // 预取的是权重，与rmsnorm即将改写的s->xb内容无关——硬件只在start之后才去
        // 读x，那时rmsnorm已经算完了
        MATMUL_PF_BEGIN(s->q, s->xb, w->wq + l*dim*dim, dim, dim, 0);

        // attention rmsnorm
        rmsnorm(s->xb, x, w->rms_att_weight + l*dim, dim);

        // KV cache layer offset（tile-based布局）
        int n_kv_heads = p->n_kv_heads;
        int max_tiles = (p->seq_len + head_size - 1) / head_size;
        int tile_size = n_kv_heads * head_size * head_size;
        int loff = l * max_tiles * tile_size;

        // qkv matmuls for this position
        MATMUL_PF_END(s->q, s->xb, w->wq + l*dim*dim, dim, dim, 0);
        matmul_nf(s->k, s->xb, w->wk + l*dim*kv_dim, dim, kv_dim);
        matmul_nf(s->v, s->xb, w->wv + l*dim*kv_dim, dim, kv_dim);

        // 预取attention要用的K tile 0，搬运藏进下面这段RoPE。
        // 必须放在上面两个matmul_nf之后——它们会写MI_BASE/ROWS/COLS，那会让预取作废。
        // FSA_PF_LATE=1 是诊断变体：把预取调用挪到 attention 紧前面，不再跨 RoPE。
        // 代码量/寄存器压力/指令数全不变，CSR 写的位置回到与基线相同，唯一区别是
        // 预取 DMA 在 attention 前一瞬才发（藏不住东西，但无害）。用来判定退化到底
        // 来自"代码跨 RoPE 移动"还是"代码增加本身"。
#if FSA_PF_LATE
        int fsa_pf_hit = 0;
#else
        int fsa_pf_hit = fsa_prefetch_k(s, p, pos, loff);
#endif

        // RoPE relative positional encoding: complex-valued rotate q and k in each head
        BP_MARK(bp_rope0);
        for (int i = 0; i < dim; i+=2) {
            // 子槽位ROPE.trig单独圈出三个超越函数：head_dim=i%head_size只有
            // head_size/2种取值，freq是循环不变量；val=pos*freq中pos为整数位置，
            // 故(fcr,fci)完全可在启动时按(pos,head_dim)预计算成表。这段实测多大，
            // 就等于查表化能省下多少——这是决定要不要做该优化的唯一依据
            BP_MARK(bp_r0);
            int head_dim = i % head_size;
#if NO_ROPE_HOIST
            /* 优化前的原始写法：每层每两个元素算一遍 powf/cosf/sinf。
             * 256 token 实测 n=40960，即每 token 算 160 次（5 层 × 32 次迭代）。 */
            float freq = 1.0f / powf(10000.0f, head_dim / (float)head_size);
            float val  = pos * freq;
            float fcr  = cosf(val);
            float fci  = sinf(val);
#else
            // 三个超越函数已提到 forward() 开头按 (pos, head_dim) 算好（见那里的说明），
            // 这里退化成一次查表。逐位等价：同函数同参数，只是不再重复算 160 次。
            float fcr = rope_fcr[head_dim >> 1];
            float fci = rope_fci[head_dim >> 1];
#endif
#if DUMP_ACT && !defined(__loongarch__)
            if (g_act_rope) {
                float val_dbg = pos * (1.0f / powf(10000.0f, head_dim / (float)head_size));
                fwrite(&val_dbg, sizeof(float), 1, g_act_rope);
            }
#endif
            BP_MARK(bp_r1);
            BP_ACC(BP_ROPE_TRIG, bp_r0, bp_r1);
            int rotn = i < kv_dim ? 2 : 1; // how many vectors? 2 = q & k, 1 = q only
            for (int v = 0; v < rotn; v++) {
                float* vec = v == 0 ? s->q : s->k; // the vector to rotate (query or key)
                float v0 = vec[i];
                float v1 = vec[i+1];
                vec[i]   = v0 * fcr - v1 * fci;
                vec[i+1] = v0 * fci + v1 * fcr;
            }
        }
        BP_MARK(bp_rope1);
        BP_ACC(BP_ROPE, bp_rope0, bp_rope1);

        // RoPE后将K/V scatter到tile-based cache（uncached写入，无需flush）
        store_kv_to_cache(s->key_cache, loff, pos, s->k, kv_dim, head_size);
        store_kv_to_cache(s->value_cache, loff, pos, s->v, kv_dim, head_size);

        // 硬件加速attention（FSA模式）
#if CPU_ONLY_ATTN
        // 纯CPU attention（标准softmax，作为精度golden）
        {
            int seq_len_attn = pos + 1;
            for (int h = 0; h < p->n_heads; h++) {
                float* q = s->q + h * head_size;
                float* att = s->att + h * p->seq_len;
                int kv_head = h / kv_mul;
                for (int t = 0; t <= pos; t++) {
                    int tile_idx = t / head_size;
                    int row_in_tile = t % head_size;
                    float* k_ptr = s->key_cache + loff
                        + tile_idx * n_kv_heads * head_size * head_size
                        + kv_head * head_size * head_size
                        + row_in_tile * head_size;
                    float score = 0.0f;
                    for (int i = 0; i < head_size; i++)
                        score += q[i] * k_ptr[i];
                    att[t] = score / sqrtf(head_size);
                }
                softmax(att, seq_len_attn);
                float* xb = s->xb + h * head_size;
                memset(xb, 0, head_size * sizeof(float));
                for (int t = 0; t <= pos; t++) {
                    int tile_idx = t / head_size;
                    int row_in_tile = t % head_size;
                    float* v_ptr = s->value_cache + loff
                        + tile_idx * n_kv_heads * head_size * head_size
                        + kv_head * head_size * head_size
                        + row_in_tile * head_size;
                    float a = att[t];
                    for (int i = 0; i < head_size; i++)
                        xb[i] += a * v_ptr[i];
                }
            }
        }
#else
#if FSA_PF_LATE
        fsa_pf_hit = fsa_prefetch_k(s, p, pos, loff);
#endif
        attention_fsa(s, p, pos, loff, fsa_pf_hit);
#endif

#if VERIFY_MATMUL
        // CPU golden attention比对（原版标准实现）
        // 注意：CPU无FPU，expf/sqrtf极慢，pos大时每token验证需数秒
        if (pos > 0) {
            verify_fsa_calls++;
            if ((verify_fsa_calls % 5) == 1)
                printf("[VERIFY_FSA] computing golden pos=%d L%llu...\r", pos, l);
            float xb_golden[64];  // dim=64
            int seq_len = pos + 1;
            float max_err = 0.0f;
            int mismatch = 0;

            for (int h = 0; h < p->n_heads; h++) {
                float* q = s->q + h * head_size;
                float att_buf[256];  // seq_len最大256
                int kv_head = h / kv_mul;

                // QK点积 + scale
                for (int t = 0; t <= pos; t++) {
                    // 从tile-based cache读取K
                    int tile_idx = t / head_size;
                    int row_in_tile = t % head_size;
                    float* k_ptr = s->key_cache + loff
                        + tile_idx * n_kv_heads * head_size * head_size
                        + kv_head * head_size * head_size
                        + row_in_tile * head_size;
                    float score = 0.0f;
                    for (int i = 0; i < head_size; i++)
                        score += q[i] * k_ptr[i];
                    att_buf[t] = score / sqrtf(head_size);
                }

                // softmax
                softmax(att_buf, seq_len);

                // PV加权求和
                float* xb_h = xb_golden + h * head_size;
                memset(xb_h, 0, head_size * sizeof(float));
                for (int t = 0; t <= pos; t++) {
                    int tile_idx = t / head_size;
                    int row_in_tile = t % head_size;
                    float* v_ptr = s->value_cache + loff
                        + tile_idx * n_kv_heads * head_size * head_size
                        + (h / kv_mul) * head_size * head_size
                        + row_in_tile * head_size;
                    for (int i = 0; i < head_size; i++)
                        xb_h[i] += att_buf[t] * v_ptr[i];
                }
            }

            // 比对xb（硬件结果）vs xb_golden（CPU结果）
            // 与TB相同的判定逻辑：近零值用绝对误差，其他用相对误差15%
            for (int i = 0; i < dim; i++) {
                float diff = fabsf(s->xb[i] - xb_golden[i]);
                if (diff > max_err) max_err = diff;
                if (fabsf(xb_golden[i]) < 0.01f) {
                    if (diff > 0.05f) mismatch++;
                } else {
                    float rel = diff / fabsf(xb_golden[i]);
                    if (rel > 0.15f) mismatch++;
                }
            }
            if (l == 0) {
                if (max_err > verify_fsa_global_max_err)
                    verify_fsa_global_max_err = max_err;
                if (mismatch > 0)
                    verify_fsa_mismatch_calls++;
            }
            // 只报告第一层（L0）的误差，排除跨层累积效应
            if (l == 0 && ((verify_fsa_calls % 80) == 0 || (mismatch > 0 && verify_fsa_mismatch_calls <= 3))) {
                printf("[VERIFY_FSA] call#%d L%llu pos=%d max_err=%.4f mismatches=%d\n",
                       verify_fsa_calls, l, pos, max_err, mismatch);
                if (mismatch > 0 && verify_fsa_mismatch_calls <= 3) {
                    for (int dbg = 0; dbg < 4 && dbg < dim; dbg++)
                        printf("  [%d] hw=%.6f golden=%.6f\n", dbg, s->xb[dbg], xb_golden[dbg]);
                }
            }
            // 打印L0和L4的score范围（验证深层score是否更极端）
            if (pos == 5 && (l == 0 || l == 4) && verify_fsa_calls <= 10) {
                float* q0 = s->q;
                float score_min = 1e10f, score_max = -1e10f;
                for (int t = 0; t <= pos; t++) {
                    int tile_idx = t / head_size;
                    int row_in_tile = t % head_size;
                    float* k_ptr = s->key_cache + loff
                        + tile_idx * n_kv_heads * head_size * head_size
                        + row_in_tile * head_size;
                    float score = 0.0f;
                    for (int i = 0; i < head_size; i++)
                        score += q0[i] * k_ptr[i];
                    score /= sqrtf(head_size);
                    if (score < score_min) score_min = score;
                    if (score > score_max) score_max = score;
                }
                printf("[SCORE_DIST] L%llu pos=%d score_range=[%.3f, %.3f] spread=%.3f\n",
                       l, pos, score_min, score_max, score_max - score_min);
                // 打印K[0][0..3]验证KV cache读取正确性
                float* k0_ptr = s->key_cache + loff;
                printf("[KV_CHECK] L%llu K[0][0..3]=%.4f %.4f %.4f %.4f loff=%d\n",
                       l, k0_ptr[0], k0_ptr[1], k0_ptr[2], k0_ptr[3], loff);
                printf("[Q_CHECK] L%llu Q[0..3]=%.4f %.4f %.4f %.4f\n",
                       l, s->q[0], s->q[1], s->q[2], s->q[3]);
            }
        }
#endif

        // final matmul to get the output of the attention
        matmul(s->xb2, s->xb, w->wo + l*dim*dim, dim, dim);

        // 预取w1的第一块。放在residual之前发，搬运能同时藏进residual和ffn rmsnorm
        // 两段CPU计算；此刻硬件刚做完wo的matmul、权重SRAM已空闲
        MATMUL_PF_BEGIN(s->hb, s->xb, w->w1 + l*dim*hidden_dim, dim, hidden_dim,
                        HW_SILU_FUSED);

        // residual connection back into x
        BP_MARK(bp_rs0);
        for (int i = 0; i < dim; i++) {
            x[i] += s->xb2[i];
        }
        BP_MARK(bp_rs1);
        BP_ACC(BP_RESIDUAL, bp_rs0, bp_rs1);
#if STAGE_HASH
        sh_rec(x, dim);   /* attention 之后 */
#endif

        // ffn rmsnorm
        rmsnorm(s->xb, x, w->rms_ffn_weight + l*dim, dim);
#if STAGE_HASH_FINE
        sh_rec(s->xb, dim);        /* F0: rmsnorm 之后 */
#endif

        // Now for FFN in PyTorch we have: self.w2(F.silu(self.w1(x)) * self.w3(x))
        // first calculate self.w1(x) and self.w3(x)
        // w1那一路开硬件SiLU融合：结果回到DDR时已经是silu(w1·x)，下面的循环
        // 不必再算expf。w3不过激活，仍走普通matmul
        MATMUL_PF_END(s->hb, s->xb, w->w1 + l*dim*hidden_dim, dim, hidden_dim,
                      HW_SILU_FUSED);
#if W1_READBACK
        /* 唤醒后立刻读回 w1 的输出（d=172，6 个行 tile：5×32 + 12），找第一个出错下标。
         * 用来区分 w2 那边观测到的 idx=32 是"第二个 tile"还是"最后一个 tile"——
         * d=64 只有两个 tile，两者重合分不开；d=172 的最后一个 tile 从 160 开始。
         *   160 → "最后一个 tile 的写来不及"，规律可推广
         *    32 → 特指第二个 tile，另一种机制
         *   无错 → w1 干净，问题特属于 w2 的形状或位置
         * 正常流程里 w1 的输出要隔一整次 w3 才被读，所以必须在这里主动读一次。 */
        {
            volatile float *hb_uc = uncached_f(s->hb);
            uint32_t e1[192];
            int nn1 = hidden_dim < 192 ? hidden_dim : 192;
            for (int k = 0; k < nn1; k++) e1[k] = f2u_bits(hb_uc[k]);
            int fb = -1, nb = 0;
            for (int k = 0; k < nn1; k++) {
                if (e1[k] != f2u_bits(hb_uc[k])) { if (fb < 0) fb = k; nb++; }
            }
            if (fb >= 0)
                printf("[W1RB] l=%d firstbad=%d nbad=%d\n", (int)l, fb, nb);
        }
#endif
#if STAGE_HASH_FINE
        sh_rec(s->hb, hidden_dim);  /* F1: w1 + 硬件融合 SiLU 之后（d=172）*/
#endif
#if CPU_W3
        /* 诊断（Makefile CPU_W3=1）：CPU_W2 的**等代价对照**。
         * w3 的形状 n=64/d=172 与 w2 的 n=172/d=64 乘加次数完全相同（11008 次），
         * 所以搬到 CPU 上带来的额外耗时也相同。用来把"绕开 w2"与"整体变慢"分开：
         *   两个都修好 → 是变慢在起作用（唤醒后多做工作 = IDLE_WARMUP）
         *   只有 CPU_W2 修好 → w2 那次调用本身就是元凶 */
        for (int i3 = 0; i3 < hidden_dim; i3++) {
            float sum3 = 0.0f;
            const float *wrow3 = w->w3 + l*dim*hidden_dim + (size_t)i3*dim;
            for (int j3 = 0; j3 < dim; j3++) sum3 += wrow3[j3] * s->xb[j3];
            s->hb2[i3] = sum3;
        }
#else
        matmul_nf(s->hb2, s->xb, w->w3 + l*dim*hidden_dim, dim, hidden_dim);
#endif
#if STAGE_HASH_FINE
        sh_rec(s->hb2, hidden_dim); /* F2: w3 之后（d=172，不过激活）*/
#endif

        // 预取w2的第一块，搬运藏进下面的SwiGLU循环（hidden_dim=172次乘加，
        // 是这几个窗口里最长的一个）
        MATMUL_PF_BEGIN(s->xb, s->hb, w->w2 + l*dim*hidden_dim, hidden_dim, dim, 0);

        // SwiGLU non-linearity
        BP_MARK(bp_ffn0);
        for (int i = 0; i < hidden_dim; i++) {
            float val = s->hb[i];
#if DUMP_ACT && !defined(__loongarch__)
            if (g_act_silu) fwrite(&val, sizeof(float), 1, g_act_silu);
#endif
            // silu(x)=x*σ(x), where σ(x) is the logistic sigmoid
            // 子槽位FFN.exp单独圈出expf：输入是数据，无法预计算，但可用FSA里
            // 已验证过的exp2分段PWL近似替代。这段实测多大即近似化的收益上限
            BP_MARK(bp_e0);
#if HW_SILU_FUSED
            // 硬件已在GEMV写回前算完silu()，val拿到手就是最终值。
            // 这里保留计时探针，好在BENCH里看到FFN.exp归零
            (void)0;
            BP_MARK(bp_e1);
            BP_ACC(BP_FFN_EXP, bp_e0, bp_e1);
#elif SILU_APPROX
            val = silu_hw_bitlevel(val);
            BP_MARK(bp_e1);
            BP_ACC(BP_FFN_EXP, bp_e0, bp_e1);
#else
            float e = expf(-val);
            BP_MARK(bp_e1);
            BP_ACC(BP_FFN_EXP, bp_e0, bp_e1);
            val *= (1.0f / (1.0f + e));
#endif
            // elementwise multiply with w3(x)
            val *= s->hb2[i];
            s->hb[i] = val;
        }
        BP_MARK(bp_ffn1);
        BP_ACC(BP_FFN_ACT, bp_ffn0, bp_ffn1);
#if STAGE_HASH_FINE
        sh_rec(s->hb, hidden_dim);  /* F3: SwiGLU 逐元素乘之后（纯 CPU）*/
#endif

        // final matmul to get the output of the ffn
#if CPU_W2
        /* 诊断（Makefile CPU_W2=1）：**只有 w2 这一次**改走纯 CPU，其余全部仍走加速器。
         * 分阶段哈希把第一处分叉 3/3 钉在 F4（w2 输出）上，而 w2 是全模型唯一
         * 列数不是 32 整数倍的矩阵乘（n=172=5×32+12，尾块 12 列）——plan 第 5 步
         * 明确警告过尾块最容易写错、且会被"现有 case 刚好整除"掩盖。
         * 这一档若乱码消失，就把范围锁死在这次调用；若照旧，说明 F4 只是错误
         * 第一次显形的位置而非产生地。 */
        for (int i2 = 0; i2 < dim; i2++) {
            float sum2 = 0.0f;
            const float *wrow = w->w2 + l*dim*hidden_dim + (size_t)i2*hidden_dim;
            for (int j2 = 0; j2 < hidden_dim; j2++) sum2 += wrow[j2] * s->hb[j2];
            s->xb[i2] = sum2;
        }
#else
#if W2_READBACK
        /* 启动之前先记下 xout[32] 的**旧内容**。它是四路判据的锚点：
         * 只有知道"没被写之前长什么样"，才能区分"新值迟到"与"旧值回填"。 */
        uint32_t w2rb_pre = f2u_bits(uncached_f(s->xb)[32]);
#endif
#if W2_PAD192
        if (!w2_pad_ready) w2_pad_build(w, dim, hidden_dim);
        for (int jp = 0; jp < hidden_dim;  jp++) hb_pad[jp] = s->hb[jp];
        for (int jp = hidden_dim; jp < W2P_COLS; jp++) hb_pad[jp] = 0.0f;
        matmul(s->xb, hb_pad, w2_pad + (size_t)l * W2P_ROWS * W2P_COLS, W2P_COLS, dim);
#elif W2_NPAD
        /* 诊断（Makefile W2_NPAD=<列数>）：把 w2 的列数改成指定值（5 个满列 tile，
         * 不再有部分列块）。**数学结果会错，这是有意的**——本探针只看 W2_READBACK
         * 的早读/晚读是否仍分叉，那个判据与数值正确性无关。
         *   [W2RB] 消失 → 部分列块（172=5×32+12，尾块 12 列）就是触发条件
         *   [W2RB] 仍在 → 列尾块无关，排除
         * w2 是全模型唯一列数非 32 整数倍的调用，而 plan 第 5 步明确警告过
         * "尾块最容易写错、且会被现有 case 刚好整除掩盖"。 */
        MATMUL_PF_END(s->xb, s->hb, w->w2 + l*dim*hidden_dim, W2_NPAD_N, dim, 0);
#else
        MATMUL_PF_END(s->xb, s->hb, w->w2 + l*dim*hidden_dim, hidden_dim, dim, 0);
#endif
#if W2_READBACK
        /* 只对 w2 这次调用做诊断：唤醒后连续轮询 xout[32]，量出"多久才稳定"。
         *
         * 上一版（全 64 字双读）已直证：第一处出错**永远是 idx=32**，九次无例外。
         * d=64、HW_ROWS=32，所以 32 正好是第二个行 tile 的起点；nbad 在 2~19 之间
         * 波动说明第二块只写了一部分。
         * 现在要的是**时间尺度**——几十拍说明只剩最后几个 beat 在排空，
         * 几百拍说明整块写还没开始。这个数字直接决定往哪个方向查。
         * 轮询本身每次约 12 拍，把它当成刻度尺。 */
        {
            volatile float *xb_uc = uncached_f(s->xb);
            uint32_t v[96];
            int NP = 96;
            for (int k = 0; k < NP; k++) v[k] = f2u_bits(xb_uc[32]);
            uint32_t fin = v[NP-1];
            int firststable = -1;
            for (int k = 0; k < NP; k++) {
                if (v[k] == fin) { firststable = k; break; }
            }
            /* CPU 侧独立算一遍 row 32，作为"正确值"的参照。累加顺序与加速器不同、
             * 末位可能差几个 ulp，但两个候选值相差一个数量级以上，粗比足以定向。
             * 这段计算放在轮询数组**采完之后**，不会扰动被测的时间窗。 */
            const float *w2r = w->w2 + (size_t)l * dim * hidden_dim
                                     + (size_t)32 * hidden_dim;
            float acc = 0.0f;
            for (int jj = 0; jj < hidden_dim; jj++) acc += w2r[jj] * s->hb[jj];
            if (firststable != 0)
                /* 四路判据：
                 *   pre==first && final≈cpu → DMA 回写迟到，done 报早了
                 *   pre==final && first≈cpu → 新值被旧值**回填覆盖**
                 *   first、final 都 ≠ cpu    → 算错了，不是搬运问题
                 *   pre 三者都不等            → 还有第四方在写这块地址 */
                printf("[W2POLL] l=%d stable=%d pre=%08x first=%08x final=%08x cpu=%08x\n",
                       (int)l, firststable, w2rb_pre, v[0], fin, f2u_bits(acc));
        }
#endif
#endif
#if STAGE_HASH_FINE
        sh_rec(s->xb, dim);         /* F4: w2 之后（n=172, d=64）*/
#endif

        // residual connection
        BP_MARK(bp_rs2);
        for (int i = 0; i < dim; i++) {
            x[i] += s->xb[i];
        }
        BP_MARK(bp_rs3);
        BP_ACC(BP_RESIDUAL, bp_rs2, bp_rs3);
#if STAGE_HASH
        sh_rec(x, dim);   /* FFN 之后 */
#endif
    }

    // final rmsnorm
    rmsnorm(x, x, w->rms_final_weight, dim);

    // classifier into logits
    matmul(s->logits, x, w->wcls, p->dim, p->vocab_size);
    return s->logits;
}

// ----------------------------------------------------------------------------
// The Byte Pair Encoding (BPE) Tokenizer that translates strings <-> tokens

typedef struct {
    char *str;
    int id;
} TokenIndex;

typedef struct {
    char** vocab;
    float* vocab_scores;
    TokenIndex *sorted_vocab;
    int vocab_size;
    unsigned int max_token_length;
    unsigned char byte_pieces[512]; // stores all single-byte strings
} Tokenizer;

int compare_tokens(const void *a, const void *b) {
    return strcmp(((TokenIndex*)a)->str, ((TokenIndex*)b)->str);
}

void build_tokenizer(Tokenizer* t, int vocab_size) {
    // i should have written the vocab_size into the tokenizer file... sigh
    t->vocab_size = vocab_size;
    // malloc space to hold the scores and the strings
    t->vocab = (char**)malloc(vocab_size * sizeof(char*));
    t->vocab_scores = (float*)malloc(vocab_size * sizeof(float));
    t->sorted_vocab = NULL; // initialized lazily
    for (int i = 0; i < 256; i++) {
        t->byte_pieces[i * 2] = (unsigned char)i;
        t->byte_pieces[i * 2 + 1] = '\0';
    }

    // MODIFICATION: Read tokenizer data from the embedded `tok512_bin` array.
    unsigned char* p_tokenizer_data = tok512_bin;
    unsigned char* end_tokenizer_data = tok512_bin + tok512_bin_len;

    // Read max_token_length
    if (p_tokenizer_data + sizeof(int) > end_tokenizer_data) {
        fprintf(stderr, "Error reading max_token_length: not enough data in tok512_bin\n");
        exit(EXIT_FAILURE);
    }
    memcpy(&t->max_token_length, p_tokenizer_data, sizeof(int));
    p_tokenizer_data += sizeof(int);

    // Read vocab and scores
    for (int i = 0; i < vocab_size; i++) {
        // Read score
        if (p_tokenizer_data + sizeof(float) > end_tokenizer_data) {
            fprintf(stderr, "Error reading vocab_score for token %d: not enough data\n", i);
            exit(EXIT_FAILURE);
        }
        memcpy(t->vocab_scores + i, p_tokenizer_data, sizeof(float));
        p_tokenizer_data += sizeof(float);

        // Read string length
        int len;
        if (p_tokenizer_data + sizeof(int) > end_tokenizer_data) {
            fprintf(stderr, "Error reading length for token %d: not enough data\n", i);
            exit(EXIT_FAILURE);
        }
        memcpy(&len, p_tokenizer_data, sizeof(int));
        p_tokenizer_data += sizeof(int);

        // Read string
        if (len < 0 || p_tokenizer_data + len > end_tokenizer_data) {
             fprintf(stderr, "Error reading vocab string for token %d: invalid length or not enough data (len: %d)\n", i, len);
             exit(EXIT_FAILURE);
        }
        t->vocab[i] = (char *)malloc(len + 1);
        if (!t->vocab[i]) { fprintf(stderr, "malloc failed: t->vocab[%d]\n", i); exit(EXIT_FAILURE); }
        memcpy(t->vocab[i], p_tokenizer_data, len);
        t->vocab[i][len] = '\0';
        p_tokenizer_data += len;
    }
}

void free_tokenizer(Tokenizer* t) {
    for (int i = 0; i < t->vocab_size; i++) { free(t->vocab[i]); }
    free(t->vocab);
    free(t->vocab_scores);
    free(t->sorted_vocab);
}

char* decode(Tokenizer* t, int prev_token, int token) {
    char *piece = t->vocab[token];
    // following BOS (1) token, sentencepiece decoder strips any leading whitespace (see PR #89)
    if (prev_token == 1 && piece[0] == ' ') { piece++; }
    // careful, some tokens designate raw bytes, and look like e.g. '<0x01>'
    // parse this and convert and return the actual byte
    unsigned char byte_val;
    if (sscanf(piece, "<0x%02hhX>", &byte_val) == 1) {
        piece = (char*)t->byte_pieces + byte_val * 2;
    }
    return piece;
}

void safe_printf(char *piece) {
    // piece might be a raw byte token, and we only want to print printable chars or whitespace
    // because some of the other bytes can be various control codes, backspace, etc.
    if (piece == NULL) { return; }
    if (piece[0] == '\0') { return; }
    if (piece[1] == '\0') {
        unsigned char byte_val = piece[0];
        if (!(isprint(byte_val) || isspace(byte_val))) {
            return; // bad byte, don't print it
        }
    }
    printf("%s", piece);
}

int str_lookup(char *str, TokenIndex *sorted_vocab, int vocab_size) {
    // efficiently find the perfect match for str in vocab, return its index or -1 if not found
    TokenIndex tok = { .str = str }; // acts as the key to search for
    TokenIndex *res = bsearch(&tok, sorted_vocab, vocab_size, sizeof(TokenIndex), compare_tokens);
    return res != NULL ? res->id : -1;
}

void encode(Tokenizer* t, char *text, int8_t bos, int8_t eos, int *tokens, int *n_tokens) {
    // encode the string text (input) into an upper-bound preallocated tokens[] array
    // bos != 0 means prepend the BOS token (=1), eos != 0 means append the EOS token (=2)
    if (text == NULL) { fprintf(stderr, "cannot encode NULL text\n"); exit(EXIT_FAILURE); }

    if (t->sorted_vocab == NULL) {
        // lazily malloc and sort the vocabulary
        t->sorted_vocab = malloc(t->vocab_size * sizeof(TokenIndex));
        for (int i = 0; i < t->vocab_size; i++) {
            t->sorted_vocab[i].str = t->vocab[i];
            t->sorted_vocab[i].id = i;
        }
        qsort(t->sorted_vocab, t->vocab_size, sizeof(TokenIndex), compare_tokens);
    }

    // create a temporary buffer that will store merge candidates of always two consecutive tokens
    // *2 for concat, +1 for null terminator +2 for UTF8 (in case max_token_length is 1)
    char* str_buffer = malloc((t->max_token_length*2 +1 +2) * sizeof(char));
    size_t str_len = 0;

    // start at 0 tokens
    *n_tokens = 0;

    // add optional BOS (=1) token, if desired
    if (bos) tokens[(*n_tokens)++] = 1;

    // add_dummy_prefix is true by default
    // so prepend a dummy prefix token to the input string, but only if text != ""
    // TODO: pretty sure this isn't correct in the general case but I don't have the
    // energy to read more of the sentencepiece code to figure out what it's doing
    if (text[0] != '\0') {
        int dummy_prefix = str_lookup(" ", t->sorted_vocab, t->vocab_size);
        if (dummy_prefix != -1) {
            tokens[(*n_tokens)++] = dummy_prefix;
        }
    }

    // process the raw (UTF-8) byte sequence of the input string
    for (char *p = text; *p != '\0';) {
        int id = -1;
        size_t len = 0;
        for (int i = 1; i <= t->max_token_length && p[i-1] != '\0'; i++) {
            memcpy(str_buffer, p, i);
            str_buffer[i] = '\0';
            int current_id = str_lookup(str_buffer, t->sorted_vocab, t->vocab_size);
            if (current_id != -1) {
                // we found a match in the vocab
                id = current_id;
                len = i;
            }
        }

        if (id != -1) {
            // we found a match, add it to the tokens and advance
            tokens[(*n_tokens)++] = id;
            p += len;
        } else {
            // we did not find any match in the vocab, fall back to byte-level token
            tokens[(*n_tokens)++] = (unsigned char)(*p) + 3;
            p++;
        }
    }

    // merge the best consecutive pair each iteration, according the scores in vocab_scores
    while (1) {
        float best_score = -1e10;
        int best_id = -1;
        int best_idx = -1;

        for (int i=0; i < (*n_tokens-1); i++) {
            // check if we can merge the pair (tokens[i], tokens[i+1])
            sprintf(str_buffer, "%s%s", t->vocab[tokens[i]], t->vocab[tokens[i+1]]);
            int id = str_lookup(str_buffer, t->sorted_vocab, t->vocab_size);
            if (id != -1 && t->vocab_scores[id] > best_score) {
                // this merge pair exists in vocab! record its score and position
                best_score = t->vocab_scores[id];
                best_id = id;
                best_idx = i;
            }
        }

        if (best_idx == -1) {
            break; // we couldn't find any more pairs to merge, so we're done
        }

        // merge the consecutive pair (best_idx, best_idx+1) into new token best_id
        tokens[best_idx] = best_id;
        // delete token at position best_idx+1, shift the entire sequence back 1
        for (int i = best_idx+1; i < (*n_tokens-1); i++) {
            tokens[i] = tokens[i+1];
        }
        (*n_tokens)--; // token length decreased
    }

    // add optional EOS (=2) token, if desired
    if (eos) tokens[(*n_tokens)++] = 2;

    free(str_buffer);
}

// ----------------------------------------------------------------------------
// The Sampler, which takes logits and returns a sampled token
// sampling can be done in a few ways: greedy argmax, sampling, top-p sampling

typedef struct {
    float prob;
    int index;
} ProbIndex; // struct used when sorting probabilities during top-p sampling

typedef struct {
    int vocab_size;
    ProbIndex* probindex; // buffer used in top-p sampling
    float temperature;
    float topp;
    unsigned long long rng_state;
} Sampler;

int sample_argmax(float* probabilities, int n) {
    // return the index that has the highest probability
    int max_i = 0;
    float max_p = probabilities[0];
    for (int i = 1; i < n; i++) {
        if (probabilities[i] > max_p) {
            max_i = i;
            max_p = probabilities[i];
        }
    }
    return max_i;
}

int sample_mult(float* probabilities, int n, float coin) {
    // sample index from probabilities (they must sum to 1!)
    // coin is a random number in [0, 1), usually from random_f32()
    float cdf = 0.0f;
    for (int i = 0; i < n; i++) {
        cdf += probabilities[i];
        if (coin < cdf) {
            return i;
        }
    }
    return n - 1; // in case of rounding errors
}

int compare(const void* a, const void* b) {
    ProbIndex* a_ = (ProbIndex*) a;
    ProbIndex* b_ = (ProbIndex*) b;
    if (a_->prob > b_->prob) return -1;
    if (a_->prob < b_->prob) return 1;
    return 0;
}

int sample_topp(float* probabilities, int n, float topp, ProbIndex* probindex, float coin) {
    // top-p sampling (or "nucleus sampling") samples from the smallest set of
    // tokens that exceed probability topp. This way we never sample tokens that
    // have very low probabilities and are less likely to go "off the rails".
    // coin is a random number in [0, 1), usually from random_f32()

    int n0 = 0;
    // quicksort indices in descending order of probabilities
    // values smaller than (1 - topp) / (n - 1) cannot be part of the result
    // so for efficiency we crop these out as candidates before sorting
    const float cutoff = (1.0f - topp) / (n - 1);
    for (int i = 0; i < n; i++) {
        if (probabilities[i] >= cutoff) {
            probindex[n0].index = i;
            probindex[n0].prob = probabilities[i];
            n0++;
        }
    }
    qsort(probindex, n0, sizeof(ProbIndex), compare);

    // truncate the list where cumulative probability exceeds topp
    float cumulative_prob = 0.0f;
    int last_idx = n0 - 1; // in case of rounding errors consider all elements
    for (int i = 0; i < n0; i++) {
        cumulative_prob += probindex[i].prob;
        if (cumulative_prob > topp) {
            last_idx = i;
            break; // we've exceeded topp by including last_idx
        }
    }

    // sample from the truncated list
    float r = coin * cumulative_prob;
    float cdf = 0.0f;
    for (int i = 0; i <= last_idx; i++) {
        cdf += probindex[i].prob;
        if (r < cdf) {
            return probindex[i].index;
        }
    }
    return probindex[last_idx].index; // in case of rounding errors
}

void build_sampler(Sampler* sampler, int vocab_size, float temperature, float topp, unsigned long long rng_seed) {
    sampler->vocab_size = vocab_size;
    sampler->temperature = temperature;
    sampler->topp = topp;
    sampler->rng_state = rng_seed;
    // buffer only used with nucleus sampling; may not need but it's ~small
    sampler->probindex = malloc(sampler->vocab_size * sizeof(ProbIndex));
}

void free_sampler(Sampler* sampler) {
    free(sampler->probindex);
}

unsigned int random_u32(unsigned long long *state) {
    // xorshift rng: https://en.wikipedia.org/wiki/Xorshift#xorshift.2A
    *state ^= *state >> 12;
    *state ^= *state << 25;
    *state ^= *state >> 27;
    return (*state * 0x2545F4914F6CDD1Dull) >> 32;
}
float random_f32(unsigned long long *state) { // random float32 in [0,1)
    return (random_u32(state) >> 8) / 16777216.0f;
}

int sample(Sampler* sampler, float* logits) {
    // sample the token given the logits and some hyperparameters
    int next;
    if (sampler->temperature == 0.0f) {
        // greedy argmax sampling: take the token with the highest probability
        next = sample_argmax(logits, sampler->vocab_size);
    } else {
        // apply the temperature to the logits
        for (int q=0; q<sampler->vocab_size; q++) { logits[q] /= sampler->temperature; }
        // apply softmax to the logits to get the probabilities for next token
        softmax(logits, sampler->vocab_size);
        // flip a (float) coin (this is our source of entropy for sampling)
        float coin = random_f32(&sampler->rng_state);
        // we sample from this distribution to get the next token
        if (sampler->topp <= 0 || sampler->topp >= 1) {
            // simply sample from the predicted probability distribution
            next = sample_mult(logits, sampler->vocab_size, coin);
        } else {
            // top-p (nucleus) sampling, clamping the least likely tokens to zero
            next = sample_topp(logits, sampler->vocab_size, sampler->topp, sampler->probindex, coin);
        }
    }
    return next;
}

// ----------------------------------------------------------------------------
// generation loop

// 64位CPU周期计数器（防止32位溢出，33MHz下130秒就溢出）
static inline unsigned long long get_cpu_clock_count_64(void) {
#ifdef __loongarch__
    unsigned long lo, hi;
    asm volatile("rdcntvl.w %0" : "=r"(lo));
    asm volatile("rdcntvh.w %0" : "=r"(hi));
    return ((unsigned long long)hi << 32) | lo;
#else
    /* host 构建只关心数值结果，周期数无意义 */
    return (unsigned long long)clock();
#endif
}

void generate(Transformer *transformer, Tokenizer *tokenizer, Sampler *sampler, char *prompt, int steps) {
    char *empty_prompt = "";
    if (prompt == NULL) { prompt = empty_prompt; }

    // encode the (string) prompt into tokens sequence
    int num_prompt_tokens = 0;
    int* prompt_tokens = (int*)malloc((strlen(prompt)+3) * sizeof(int));
    encode(tokenizer, prompt, 1, 0, prompt_tokens, &num_prompt_tokens);
    if (num_prompt_tokens < 1) {
        fprintf(stderr, "something is wrong, expected at least 1 prompt token\n");
        exit(EXIT_FAILURE);
    }

    // token序列记录
    // 上限做成可覆盖：板上默认仍是 256（多开一倍要多占 2KB，板上内存不宽裕），
    // host 离线评估时用 -DTOKEN_HIST_MAX=512 提到模型 seq_len，让 token 级一致率
    // 能覆盖整条序列——否则 256 之后的分歧只体现在文本 diff 里，统计数字不诚实。
#ifndef TOKEN_HIST_MAX
#define TOKEN_HIST_MAX 256
#endif
    int token_history[TOKEN_HIST_MAX];
    int token_history_len = 0;
    // logits统计：每个位置记录argmax token的logit值（用于PPL计算）
    float logit_at_next[TOKEN_HIST_MAX];  // logits[next_token]，用于计算cross-entropy

    // start the main loop
    unsigned long long start_cycles = get_cpu_clock_count_64();
    int emitted_tokens = 0;
    int next;
    int token = prompt_tokens[0];
    int pos = 0;
    while (pos < steps) {

        float* logits = forward(transformer, token, pos);

        if (pos < num_prompt_tokens - 1) {
            next = prompt_tokens[pos + 1];
        } else {
            BP_MARK(bp_sp0);
            next = sample(sampler, logits);
            BP_MARK(bp_sp1);
            BP_ACC(BP_SAMPLE, bp_sp0, bp_sp1);
        }

        // 记录next token对应的logit值（softmax前）
        if (token_history_len < TOKEN_HIST_MAX)
            logit_at_next[token_history_len] = logits[next];

        pos++;
        if (next == 1) { break; }

        // 打印生成文本
        // 串口是阻塞式输出，波特率远低于CPU主频，这段有可能并不便宜；
        // 单独计时以确认它是否污染了端到端数字（真实部署时不会有这个开销）
        BP_MARK(bp_io0);
        char* piece = decode(tokenizer, token, next);
        safe_printf(piece);
        fflush(stdout);
        BP_MARK(bp_io1);
        BP_ACC(BP_IO, bp_io0, bp_io1);
        token = next;
        emitted_tokens++;

#if BENCH_TOKEN_REPORT_INTERVAL > 0
        // 每N个token报一次累计进度：KV cache随pos增长，attention开销会逐步上升，
        // 靠这个能看出每token代价是否随序列变长而漂移，而不只是拿到一个平均值
        if ((emitted_tokens % BENCH_TOKEN_REPORT_INTERVAL) == 0) {
            unsigned long long so_far = get_cpu_clock_count_64() - start_cycles;
            printf("\n[BENCH] token_progress emitted=%d cycles=%llu per_token=%llu\n",
                   emitted_tokens, so_far, so_far / (unsigned long long)emitted_tokens);
        }
#endif

        // 记录token ID
        if (token_history_len < TOKEN_HIST_MAX)
            token_history[token_history_len++] = next;
    }
    printf("\n");

    // 性能统计
    unsigned long long end_cycles = get_cpu_clock_count_64();
    unsigned long long total_cycles = end_cycles - start_cycles;
    unsigned long long cpt = emitted_tokens > 0 ? (total_cycles / (unsigned long long)emitted_tokens) : 0;

    printf("\n[HWSW] mode=%s emitted=%d total_cycles=%llu cycles_per_token=%llu\n",
           HWSW_MODE_NAME, emitted_tokens, total_cycles, cpt);

#if IDLE_WAKECNT
    printf("[IDLECNT] waits=%lu early_done=%lu spurious=%lu\n",
           idle_wait_total, idle_wake_zero, idle_wake_extra);
    for (int si = 0; si < idle_samp_n; si++)
        printf("[IDLESAMP] %d estat=%08lx crmd=%08lx\n",
               si, idle_samp_estat[si], idle_samp_crmd[si]);
#endif

#if STAGE_HASH
    sh_dump();   /* 全部算完再打印，计算过程中零串口输出 */
#endif

    // 时间拆解报告：把总周期按 CSR配置/flush/等硬件/纯CPU 归因，
    // 并给出硬件段的DMA与计算理论下限，判断瓶颈在带宽还是算力
    bp_report(total_cycles, emitted_tokens);

#if DUMP_TOKEN_SEQ
    // token序列：与另一模式(cpu/hw)逐位比对，算一致率
    printf("[HWSW] token_seq:");
    for (int i = 0; i < token_history_len; i++)
        printf(" %d", token_history[i]);
    printf("\n");
#endif

#if DUMP_LOGITS
    // logit序列：做PPL/KL精度对比用。输出很长，会淹没demo观感，故默认关闭；
    // logit_at_next数组始终在记录，打开本开关即可导出
    printf("[HWSW] logit_at_next:");
    for (int i = 0; i < token_history_len; i++)
        printf(" %.4f", logit_at_next[i]);
    printf("\n");
#endif

    free(prompt_tokens);
}

void read_stdin(const char* guide, char* buffer, size_t bufsize) {
    // 裸机直接从UART读取一行（不依赖fgets/stdin）
    printf("%s", guide);
    extern unsigned char uart_getchar(void);
    size_t i = 0;
    while (i < bufsize - 1) {
        unsigned char c = uart_getchar();
        if (c == '\r' || c == '\n') {
            printf("\r\n");
            break;
        }
        if (c == 0x7f || c == '\b') {  // 退格处理
            if (i > 0) { i--; printf("\b \b"); }
            continue;
        }
        buffer[i++] = c;
        printf("%c", c);  // 回显
    }
    buffer[i] = '\0';
}

// ----------------------------------------------------------------------------
// chat loop
// I manually inspected the tokens for a few chat conversations compared to
// python reference and that seemed ok, but this was not thoroughly tested and
// is not safely implemented, it's more a proof of concept atm.

void chat(Transformer *transformer, Tokenizer *tokenizer, Sampler *sampler,
          char *cli_user_prompt, char *cli_system_prompt, int steps) {

    // buffers for reading the system prompt and user prompt from stdin
    // you'll notice they are soomewhat haphazardly and unsafely set atm
    char system_prompt[512];
    char user_prompt[512];
    char rendered_prompt[1152];
    int num_prompt_tokens = 0;
    int* prompt_tokens = (int*)malloc(1152 * sizeof(int));
    int user_idx;

    // start the main loop
    int8_t user_turn = 1; // user starts
    int next;        // will store the next token in the sequence
    int token;       // stores the current token to feed into the transformer
    int prev_token;
    int pos = 0;     // position in the sequence
    while (pos < steps) {

        // when it is the user's turn to contribute tokens to the dialog...
        if (user_turn) {
            // get the (optional) system prompt at position 0
            if (pos == 0) {
                // at position 0, the user can also contribute a system prompt
                if (cli_system_prompt == NULL) {
                    // system prompt was not passed in, attempt to get it from stdin
                    read_stdin("Enter system prompt (optional): ", system_prompt, sizeof(system_prompt));
                } else {
                    // system prompt was passed in, use it
                    strcpy(system_prompt, cli_system_prompt);
                }
            }
            // get the user prompt
            if (pos == 0 && cli_user_prompt != NULL) {
                // user prompt for position 0 was passed in, use it
                strcpy(user_prompt, cli_user_prompt);
            } else {
                // otherwise get user prompt from stdin
                read_stdin("User: ", user_prompt, sizeof(user_prompt));
            }
            // render user/system prompts into the Llama 2 Chat schema
            if (pos == 0 && system_prompt[0] != '\0') {
                char system_template[] = "[INST] <<SYS>>\n%s\n<</SYS>>\n\n%s [/INST]";
                sprintf(rendered_prompt, system_template, system_prompt, user_prompt);
            } else {
                char user_template[] = "[INST] %s [/INST]";
                sprintf(rendered_prompt, user_template, user_prompt);
            }
            // encode the rendered prompt into tokens
            encode(tokenizer, rendered_prompt, 1, 0, prompt_tokens, &num_prompt_tokens);
            user_idx = 0; // reset the user index
            user_turn = 0;
            printf("Assistant: ");
        }

        // determine the token to pass into the transformer next
        if (user_idx < num_prompt_tokens) {
            // if we are still processing the input prompt, force the next prompt token
            token = prompt_tokens[user_idx++];
        } else {
            // otherwise use the next token sampled from previous turn
            token = next;
        }
        // EOS (=2) token ends the Assistant turn
        if (token == 2) { user_turn = 1; }

        // forward the transformer to get logits for the next token
        float* logits = forward(transformer, token, pos);
        next = sample(sampler, logits);
        pos++;

        if (user_idx >= num_prompt_tokens && next != 2) {
            // the Assistant is responding, so print its output
            char* piece = decode(tokenizer, token, next);
            safe_printf(piece); // same as printf("%s", piece), but skips "unsafe" bytes
            fflush(stdout);
        }
        if (next == 2) { printf("\n"); }
    }
    printf("\n");
    free(prompt_tokens);
}


// ----------------------------------------------------------------------------
// CLI, include only if not testing
#ifndef TESTING

void error_usage() {
    fprintf(stderr, "Usage:   run [options]\n");
    fprintf(stderr, "Example: run -n 256 -i \"Once upon a time\"\n");
    fprintf(stderr, "Options:\n");
    fprintf(stderr, "  -t <float>  temperature in [0,inf], default 1.0\n");
    fprintf(stderr, "  -p <float>  p value in top-p (nucleus) sampling in [0,1] default 0.9\n");
    fprintf(stderr, "  -s <int>    random seed, default time(NULL)\n");
    fprintf(stderr, "  -n <int>    number of steps to run for, default 256. 0 = max_seq_len\n");
    fprintf(stderr, "  -i <string> input prompt\n");
    fprintf(stderr, "  -m <string> mode: generate|chat, default: generate\n");
    fprintf(stderr, "  -y <string> (optional) system prompt in chat mode\n");
    exit(EXIT_FAILURE);
}

int main(int argc, char *argv[]) {

    // 生成token数。板上默认256；RTL仿真跑不到那么远，用 make STEPS=16 编一个
    // 短推理版本，好让推理真正结束、打印出完整的[BENCH]分段归因报告
    // （token_progress只有总周期，拿不到GEMV.csr/GEMV.hw这类分段数据）。
#ifndef GEN_STEPS
#define GEN_STEPS 256
#endif

    // default parameters
    float temperature = 1.0f;
    float topp = 0.9f;
    int steps = GEN_STEPS;
    char *prompt = NULL;
    unsigned long long rng_seed = 0;
    char *mode = "generate";
    char *system_prompt = NULL;

    // poor man's C argparse
    for (int i = 1; i < argc; i+=2) {
        // must have a value after i
        if (i + 1 >= argc) { error_usage(); }
        if (argv[i][0] != '-') { error_usage(); }
        if (strlen(argv[i]) != 2) { error_usage(); }
        // read in the args
        if (argv[i][1] == 't') { temperature = atof(argv[i + 1]); }
        else if (argv[i][1] == 'p') { topp = atof(argv[i + 1]); }
        else if (argv[i][1] == 's') { rng_seed = atoi(argv[i + 1]); }
        else if (argv[i][1] == 'n') { steps = atoi(argv[i + 1]); }
        else if (argv[i][1] == 'i') { prompt = argv[i + 1]; }
        else if (argv[i][1] == 'm') { mode = argv[i + 1]; }
        else if (argv[i][1] == 'y') { system_prompt = argv[i + 1]; }
        else { error_usage(); }
    }

    // 精度对比模式：强制temperature=0（greedy argmax），确保确定性输出
    if (rng_seed <= 0) rng_seed = 42;
    temperature = 0.0f;
    if (steps < 0) steps = 0;

    printf("[HWSW] mode=%s steps=%d\n", HWSW_MODE_NAME, steps);

#if DUMP_ACT && !defined(__loongarch__)
    g_act_silu = fopen("act_silu.bin", "wb");
    g_act_rope = fopen("act_rope.bin", "wb");
    printf("[HWSW] DUMP_ACT: act_silu.bin / act_rope.bin\n");
#endif

    // build the Transformer via the model .bin file
    Transformer transformer;
    build_transformer(&transformer);
    if (steps == 0 || steps > transformer.config.seq_len) steps = transformer.config.seq_len;

    // 一次性flush所有权重（只读静态数据，后续matmul不再重复flush）
    {
        Config* p = &transformer.config;
        TransformerWeights* w = &transformer.weights;
        size_t total_weight_bytes = (size_t)((char*)w->wcls + p->vocab_size * p->dim * sizeof(float)
                                   - (char*)w->token_embedding_table);
        cache_flush(w->token_embedding_table, total_weight_bytes);
    }

    // build the Tokenizer via the tokenizer .bin file
    Tokenizer tokenizer;
    build_tokenizer(&tokenizer, transformer.config.vocab_size);

    // build the Sampler
    Sampler sampler;
    build_sampler(&sampler, transformer.config.vocab_size, temperature, topp, rng_seed);

    // run!
#if BENCH_PROFILE
    // 含建表/编码等generate外围开销的整段耗时，与generate内部统计的total_cycles
    // 相减即可看出推理主循环之外还有多少固定开销
    unsigned long long phase_begin = get_cpu_clock_count_64();
#endif
    generate(&transformer, &tokenizer, &sampler, prompt, steps);
#if BENCH_PROFILE
    printf("[BENCH] phase_run cycles=%llu\n", get_cpu_clock_count_64() - phase_begin);
#endif

#if DUMP_ACT && !defined(__loongarch__)
    if (g_act_silu) fclose(g_act_silu);
    if (g_act_rope) fclose(g_act_rope);
#endif

    // memory and file handles cleanup
    free_sampler(&sampler);
    free_tokenizer(&tokenizer);
    free_transformer(&transformer);
    return 0;
}
#endif
