// FSA 单次调用周期数探针 filelist（性能回归定标）
// 与 fsa_e2e_filelist.f 同一套 RTL，仅换 tb（去掉 DPI golden）
rtl/sram_synth_wrapper.sv
soc/rtl/ip/ram_wrap/fpga_sram_dp.v
rtl/PE/RawFloat_SplitIF.sv
rtl/PE/RawFloat_FMA_LA.sv
rtl/PE/RawFloat_MulAddExp2.sv
rtl/PE/FPMacUnit.sv
rtl/PE/PE_retimed.sv
rtl/PE/fpadd_seq_2stage.sv
rtl/PE/fp_pre_add.sv
rtl/fpmul_seq_pipeline.sv
rtl/fpadd_seq.sv
rtl/PE_core_v2.sv
rtl/fsa/fsa_ctrl_fsm.sv
rtl/fsa/silu_ctrl_fsm.sv
rtl/fsa_gen/chisel_fsa_fp32/FPCmpUnit.sv
rtl/fsa_gen/chisel_fsa_fp32/fp32_comparator.sv
rtl/fsa_gen/chisel_fsa_fp32/CMP.sv
rtl/fsa/RawFloat_Div.sv
rtl/fsa/FPAccUnit_pipe.sv
rtl/fsa/fsa_accumulator.sv
rtl/fsa/fsa_acc_sram.sv
rtl/write_out_v2.sv
rtl/mac_top_v2.sv
rtl/cb_controll_v2.sv
rtl/axi_dma_controller.sv
rtl/axi2sram_sp_ext.sv
rtl/CB_top_v2.sv
tb/tb_axi_ram_sp_ext.sv
tb/tb_fsa_perf_probe.sv
